//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APP_SEC_NEW_F {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APP_SEC_NEW_F() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.APP_SEC_NEW_F", typeof(APP_SEC_NEW_F).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่า.
        /// </summary>
        internal static string APP_SEC_NEW_F_CONFIRM {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่าเอกสารและข้อความข้างต้นเป็นความจริงทุกประการ.
        /// </summary>
        internal static string APP_SEC_NEW_F_CONFIRM_CHECK_BOX {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_CONFIRM_CHECK_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;คำรับรองของผู้ขอรับใบอนุญาต&lt;/p&gt;&lt;br&gt;
        ///&lt;p&gt;1.&amp;nbsp;&amp;nbsp;บริษัทมีคุณสมบัติครบถ้วนตามที่กำหนดในกฎกระทรวงว่าด้วยการอนุญาตการประกอบธุรกิจหลักทรัพย์ พ.ศ. 2551 ซึ่งออกตามความในพระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535&lt;/p&gt;&lt;br&gt;
        ///&lt;p&gt;2.&amp;nbsp;&amp;nbsp;ผู้ถือหุ้นรายใหญ่ กรรมการ ผู้จัดการ และบุคคลผู้มีอำนาจในการจัดการของบริษัทมีคุณสมบัติครบถ้วน และไม่มี ลักษณะต้องห้ามตามที่กำหนดในพระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535 และประกาศที่ออกโดยอาศัยอำนาจแห่งกฎหมายดังกล่าว&lt;/p&gt;&lt;br&gt;
        ///&lt;p&gt;3.&amp;nbsp;&amp;nbsp;ข้อความในแบ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string APP_SEC_NEW_F_CONFIRM_INFO {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_CONFIRM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลเจ้าหน้าที่ผู้ขอรับใบอนุญาตที่สำนักงาน ก.ล.ต. ติดต่อได้.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_EMAIL_1 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_EMAIL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_EMAIL_2 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_EMAIL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรสาร.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_FAX_1 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_FAX_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรสาร.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_FAX_2 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_FAX_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_FIRST_NAME_1 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_FIRST_NAME_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_FIRST_NAME_2 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_FIRST_NAME_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับที่ 1.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_HEADER_1 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_HEADER_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับที่ 2.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_HEADER_2 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_HEADER_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_LAST_NAME_1 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_LAST_NAME_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_LAST_NAME_2 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_LAST_NAME_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำแหน่ง.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_POSITION_1 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_POSITION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำแหน่ง.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_POSITION_2 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_POSITION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_TELL_1 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_TELL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_TELL_2 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_TELL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้าชื่อ.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_TITLE_1 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_TITLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้าชื่อ.
        /// </summary>
        internal static string APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_TITLE_2 {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_OFFICER_SECTION_CONTACT_TITLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการประกอบธุรกิจหลักทรัพย์ประเภทกิจการการยืมและให้ยืมหลักทรัพย์.
        /// </summary>
        internal static string APP_SEC_NEW_F_SECTION_GROUP {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_SECTION_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลสถานะผู้ขอรับใบอนุญาต.
        /// </summary>
        internal static string APP_SEC_NEW_F_SECTION_REQUEST_INFO {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_SECTION_REQUEST_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะผู้ขอรับใบอนุญาต.
        /// </summary>
        internal static string APP_SEC_NEW_F_SECTION_REQUEST_INFO_CONTROL {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_SECTION_REQUEST_INFO_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุ.
        /// </summary>
        internal static string APP_SEC_NEW_F_SECTION_REQUEST_OTHER {
            get {
                return ResourceManager.GetString("APP_SEC_NEW_F_SECTION_REQUEST_OTHER", resourceCulture);
            }
        }
    }
}
