//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class APP_CLINIC_OVER_NIGHT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APP_CLINIC_OVER_NIGHT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.APP_CLINIC_OVER_NIGHT", typeof(APP_CLINIC_OVER_NIGHT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการชำระค่าธรรมเนียมการประกอบกิจการสถานพยาบาล (โรงพยาบาล).
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_GROUP {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลสถานพยาบาล (โรงพยาบาล).
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_A {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสถานพยาบาล (โรงพยาบาล).
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_A {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่ใบอนุญาตประกอบกิจการ.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_B {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ดำเนินการในปัจจุบัน.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_D {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้า.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_E {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_F {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_G {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_A_CONTROL_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียม.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_B {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีความประสงค์ชำระค่าธรรมเนียม ประจำปี (พ.ศ).
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_A {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียมการประกอบกิจการสถานพยาบาล (บาท).
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_B {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าได้แนบเอกสารหลักฐาน.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_C {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่าเอกสารและข้อมูลข้างต้นเป็นความจริงทุกประการ.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_C_CHK_A {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_C_CHK_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;B&gt;ข้าพเจ้าได้แนบเอกสารหลักฐาน มาพร้อมกับคำขอนี้ (พร้อมรับรองสำเนาถูกต้อง)&lt;/B&gt;&lt;br/&gt;
        ///&lt;span style=&quot;margin-left: 1em;&quot;&gt; &amp;#9675; รายงานประจำปี (ส.พ.24)&lt;/span&gt;&lt;br&gt;.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_C_INFO {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_C_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเตียงทั้งหมด.
        /// </summary>
        public static string APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_D {
            get {
                return ResourceManager.GetString("APP_CLINIC_OVER_NIGHT_SECTION_B_CONTROL_D", resourceCulture);
            }
        }
    }
}
