//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESOURCE_APP_CLINIC_OWNED {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCE_APP_CLINIC_OWNED() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.RESOURCE_APP_CLINIC_OWNED", typeof(RESOURCE_APP_CLINIC_OWNED).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการอ้างอิง.
        /// </summary>
        public static string APP_CLINIC_OPERATION_SECA {
            get {
                return ResourceManager.GetString("APP_CLINIC_OPERATION_SECA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่อ้างอิงคำขอใบอนุญาตประกอบกิจการสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_OPERATION_SECA_CONA {
            get {
                return ResourceManager.GetString("APP_CLINIC_OPERATION_SECA_CONA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้ดำเนินการสถานพยาบาลและผู้ปฏิบัติงานในสถานพยาบาล (ส.พ.6 และ ส.พ.18).
        /// </summary>
        public static string APP_CLINIC_OWNED {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้ดำเนินการและผู้ปฏิบัติงานในสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_OWNED_CONFIRM_SECTION {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_CONFIRM_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่า.
        /// </summary>
        public static string APP_CLINIC_OWNED_CONFIRM_SECTION_CONFIRM_TRUE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_CONFIRM_SECTION_CONFIRM_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้ดำเนินการและผู้ปฏิบัติงานในสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลผู้ดำเนินการและผู้ปฏิบัติงานในสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_ADD {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อายุ (ปี).
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_AGE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขา.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทันตกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_DENTAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_DENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การประกอบโรคศิลปะ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_MEDICAL_PRACTICE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_MEDICAL_PRACTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เทคนิคการแพทย์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_MEDICAL_TECHNIQUE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_MEDICAL_TECHNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวชกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_MEDICINE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_MEDICINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การพยาบาลและการผดุงครรภ์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_MIDWIFERY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_MIDWIFERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เฉพาะทางโรคมะเร็ง.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_CANCER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_CANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เฉพาะทางทันตกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_DENTAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_DENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เฉพาะทาง หู คอ จมูก.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_EAR_NOSE_THROAT {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_EAR_NOSE_THROAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เฉพาะทางโรคหัวใจ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_HEART_DISEASE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_HEART_DISEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เฉพาะทางอื่นๆ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_OTHER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_ONLY_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กายภาพบำบัด.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_PHYSICAL_THERAPY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_PHYSICAL_THERAPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เฉพาะทางเวชกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_SPECIALIZED_MEDICINE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_SPECIALIZED_MEDICINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เฉพาะทางด้านการพยาบาลและผดุงครรภ์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_SPECIALIZED_MIDWIFERY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_SPECIALIZED_MIDWIFERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การแพทย์แผนไทย.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_THAI_TRADITIONAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_BRANCH_THAI_TRADITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK_NATIONALITY.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CHECK_NATIONALITY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CHECK_NATIONALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานพยาบาลมีลักษณะเป็น.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกการแพทย์แผนไทยประยุกต์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_APPLIED_THAI_TRADITIONAL_MEDICINE_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_APPLIED_THAI_TRADITIONAL_MEDICINE" +
                        "_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกทันตกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_DENTAL_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_DENTAL_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกเวชกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_MEDICAL_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_MEDICAL_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกเทคนิคการแพทย์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_MEDICAL_TECHNOLOGY_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_MEDICAL_TECHNOLOGY_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกการประกอบโรคศิลปะ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_MEDICINE_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_MEDICINE_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกการพยาบาลและการผดุงครรภ์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_MIDWIFERY_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_MIDWIFERY_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกเฉพาะทางทันตกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_SPECIALIZED_DENTAL_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_SPECIALIZED_DENTAL_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกเฉพาะทางเวชกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_SPECIALIZED_MEDICAL_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_SPECIALIZED_MEDICAL_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกเฉพาะทางด้านการพยาบาลและผดุงครรภ์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_SPECIALTY_CLINICS_MIDWIFERY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_SPECIALTY_CLINICS_MIDWIFERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลินิกการแพทย์แผนไทย.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_THAI_TRADITIONAL_MEDICINE_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_THAI_TRADITIONAL_MEDICINE_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สหคลินิก.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_UNITED_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_DETAIL_UNITED_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_OTHER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขาจิตวิทยาคลินิก.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_CLINICAL_PSYCHOLOGY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_CLINICAL_PSYCHOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขาเทคโนโลยีหัวใจและทรวงอก.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_HEART_AND_CHEST_TECHNOLOGY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_HEART_AND_CHEST_TECHNOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขาการแก้ไขความผิดปกติของการสื่อความหมาย.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_INTERPRETATION_DISORDERS {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_INTERPRETATION_DISORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขากายอุปกรณ์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_ORTHOTICS {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_ORTHOTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่นๆ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_OTHER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขารังสีเทคนิค.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_TECHNICAL_RADIATION {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_TECHNICAL_RADIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขากิจกรรมบำบัด.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_THERAPY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_THERAPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขาการแพทย์แผนจีน.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_TRADITIONAL_CHINESE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CLINIC_TYPE_TRADITIONAL_CHINESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้ายินดีที่จะปฎิบัติงานในสถานพยาบาลนี้ โดยปฏิบัติงานตามวัน/เวลา ดังต่อไปนี้.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_CONFIRM_WOKING {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_CONFIRM_WOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันและเวลาปฏิบัติงานของที่ทำงานปัจจุบัน.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_DAY_TIME_WOKING {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_DAY_TIME_WOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกข้อมูลสำหรับ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_DETAIL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ปฎิบัติงาน.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_DETAIL_EMPLOYEE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_DETAIL_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ดำเนินการ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_DETAIL_OPARETOR {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_DETAIL_OPARETOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วุฒิบัตร/หนังสืออนุมัติ/หนังสือรับรอง.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_DIPLOMA {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_DIPLOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_EMAIL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะการดำเนินการในปัจจุบันของคุณเป็นอย่างไร.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ได้รับราชการหรือทำงานอยู่แห่งใด.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_1 {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่เคยเป็นผู้ประกอบวิชาชีพในสถานพยาบาลเอกชนแห่งใดมาก่อน.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_2 {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เคยเป็นผู้ประกอบวิชาชีพในสถานพยาบาลเอกชน.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_3 {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เป็นผู้ดำเนินการสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_4 {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เป็นผู้ประกอบวิชาชีพหรือปฏิบัติงานหน้าที่อื่นในสถานพยาบาล หรือในส่วนราชการ หรือหน่วยงานอื่น.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_5 {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_EMPLOYEE_STATUS_TYPE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;ไม่มีข้อมูล ข้อมูลผู้ดำเนินการและผู้ปฏิบัติงานในสถานพยาบาล ในขณะนี้ คุณสามารถเพิ่มข้อมูลข้อมูลผู้ดำเนินการและผู้ปฏิบัติงานในสถานพยาบาล&lt;/div&gt;
        ///&lt;div&gt;โดยคลิกที่ปุ่ม&quot;เพิ่มข้อมูลผู้ดำเนินการและผู้ปฏิบัติงานในสถานพยาบาล&quot;&lt;/div&gt;.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_EMPTY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_FIRSTNAME {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลผู้ป่วยเรื้อรัง.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_CHRONIC_PATIENTS {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_CHRONIC_PATIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลบำบัดยาเสพติด.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_DRUG_TREATMENT {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_DRUG_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลผู้สูงอายุ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_ELDERLY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_ELDERLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลแม่และเด็ก.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_MOTHER_CHILD {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_MOTHER_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะประเภทผู้ป่วยอื่นๆ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_OTHER_PATIENTS {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_OTHER_PATIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลผู้ป่วยจิตเวช.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_PSYCHIATRIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_PSYCHIATRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะประเภทผู้ป่วย.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_SPECIFIC_PATIENT {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_CHOICE_SPECIFIC_PATIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานพยาบาลมีลักษณะเป็น.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลทันตกรรม.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_DENTAL_HOSPITAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_DENTAL_HOSPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลทั่วไป.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_GENERAL_HOSPITAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_GENERAL_HOSPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลการพยาบาลและการผดุงครรภ์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_MIDWIFERY_HOSPITAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_MIDWIFERY_HOSPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลกายภาพบำบัด.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_PHYSICAL_THERAPY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_PHYSICAL_THERAPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะทางโรคมะเร็ง.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIALIZED_CANCER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIALIZED_CANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะทาง หู คอ จมูก.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIALIZED_EAR {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIALIZED_EAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะทาง โรคหัวใจ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIALIZED_HEART_DISEASE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIALIZED_HEART_DISEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะทางอื่นๆ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIALIZED_OTHER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIALIZED_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะประเภทผู้ป่วย.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIFIC_PATIENT {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_SPECIFIC_PATIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลการแพทย์แผนไทย.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_THAI_TRADITIONAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_THAI_TRADITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลการแพทย์แผนไทยประยุกต์.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_THAI_TRADITIONAL_APPLIED {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_DETAIL_THAI_TRADITIONAL_APPLIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_OTHER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทสถานพยาบาลที่ทำงานอยู่ในปัจจุบัน.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_TYPE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทที่ไม่รับผู้ป่วยไว้ค้างคืน (คลินิก).
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_TYPE_CLINIC {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_TYPE_CLINIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทที่รับผู้ป่วยไว้ค้างคืน (โรงพยาบาล).
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_TYPE_HOSPITAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_HOSPITAL_TYPE_HOSPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน 13 หลัก.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_ID {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_LASTNAME {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่ใบอนุญาตประกอบวิชาชีพหรือใบอนุญาตประกอบโรคศิลปะ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_LICENSE_NUMBER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_LICENSE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ออกใบอนุญาต.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_LICENSING_DATE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_LICENSING_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_MEDICAL_CENTER_ADDRESS {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_MEDICAL_CENTER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญชาติ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_NATIONALITY {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_NATIONALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะการดำเนินการในปัจจุบันของคุณเป็นอย่างไร.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_OPARETOR_STATUS {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_OPARETOR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เป็นผู้ดำเนินการสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_OPARETOR_STATUS_TYPE_1 {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_OPARETOR_STATUS_TYPE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เป็นผู้ประกอบวิชาชีพหรือปฏิบัติงานหน้าที่อื่นในสถานพยาบาล หรือในส่วนราชการ หรือหน่วยงานอื่น.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_OPARETOR_STATUS_TYPE_2 {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_OPARETOR_STATUS_TYPE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_OWNER_ADDRESS {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_OWNER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนังสือเดินทาง.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_PASSPORT {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_PASSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ได้เลิกเป็นผู้ประกอบวิชาชีพ ณ สถานพยาบาลดังกล่าวตั้งแต่วันที่.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_QUIT_WOKING_DATE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_QUIT_WOKING_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลผู้ดำเนินการและผู้ปฏิบัติงานในสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_SUBMIT {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้าชื่อ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_TITLE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เป็นผู้ประกอบวิชาชีพ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประกอบโรคศิลปะ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_TYPE_MEDICAL {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_TYPE_MEDICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประกอบวิชาชีพ.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_TYPE_PROFESSION {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_TYPE_PROFESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่ใบอนุญาตให้ดำเนินการสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_WOKING_LICENSE_NUMBER {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_WOKING_LICENSE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสถานพยาบาลที่ทำงานอยู่ในปัจจุบัน.
        /// </summary>
        public static string APP_CLINIC_OWNED_OPARETOR_SECTION_WOKING_PLACE_NAME {
            get {
                return ResourceManager.GetString("APP_CLINIC_OWNED_OPARETOR_SECTION_WOKING_PLACE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่าเอกสารและข้อความข้างต้นเป็นความจริงทุกประการ.
        /// </summary>
        public static string CLINIC_CHECKED_TRUE {
            get {
                return ResourceManager.GetString("CLINIC_CHECKED_TRUE", resourceCulture);
            }
        }
    }
}
