//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESOURCE_APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCE_APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.RESOURCE_APP_ORGANIC_PLANT_PRODUCTION_RENEW_SE" +
                            "ARCH", typeof(RESOURCE_APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหาข้อมูล.
        /// </summary>
        public static string APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH {
            get {
                return ResourceManager.GetString("APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหาใบรับรองที่ต้องการต่ออายุ.
        /// </summary>
        public static string APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION {
            get {
                return ResourceManager.GetString("APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน 13 หลัก.
        /// </summary>
        public static string APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_CITIZEN_ID {
            get {
                return ResourceManager.GetString("APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_CITIZEN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขทะเบียนนิติบุคคล 13 หลัก.
        /// </summary>
        public static string APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_JURISTIC_ID {
            get {
                return ResourceManager.GetString("APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_JURISTIC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกใบรับรองที่ต้องการต่ออายุ.
        /// </summary>
        public static string APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_LICENSE_RENEW {
            get {
                return ResourceManager.GetString("APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_LICENSE_RENEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบที่ 1.
        /// </summary>
        public static string APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_LICENSE_RENEW_RENEW_1 {
            get {
                return ResourceManager.GetString("APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_LICENSE_RENEW_RENEW_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบที่ 2.
        /// </summary>
        public static string APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_LICENSE_RENEW_RENEW_2 {
            get {
                return ResourceManager.GetString("APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_LICENSE_RENEW_RENEW_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        public static string APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_SEARCH {
            get {
                return ResourceManager.GetString("APP_ORGANIC_PLANT_PRODUCTION_RENEW_SEARCH_SEARCH_SECTION_SEARCH", resourceCulture);
            }
        }
    }
}
