//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESOURCE_APP_HOSPITAL_PERMISSION_CANCEL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCE_APP_HOSPITAL_PERMISSION_CANCEL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.RESOURCE_APP_HOSPITAL_PERMISSION_CANCEL", typeof(RESOURCE_APP_HOSPITAL_PERMISSION_CANCEL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลคำขอยกเลิกใบอนุญาตให้ประกอบกิจการสถานพยาบาลหรือใบอนุญาตให้ดำเนินการสถานพยาบาลประเภทที่รับผู้ป่วยค้างคืน (ส.พ.17).
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลคำขอยกเลิกให้ประกอบกิจการสถานพยาบาล(ประเภทที่รับผู้ป่วยค้างคืน).
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่า.
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_CONFIRM_PERMISSION {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_CONFIRM_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_CONFIRM_PERMISSION_INFO {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_CONFIRM_PERMISSION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งแต่วันที่.
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_DATE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาแนบใบอนุญาตให้ประกอบกิจการสถานพยาบาล (ส.พ.7) ใบอนุญาตให้ดำเนินการสถานพยาบาล (ส.พ.19 ) และสมุดทะเบียนสถานพยาบาล ตัวจริงมาในวันที่พบหน่วยงาน.
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_INFO {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ออกใบอนุญาต.
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_LICENSING_DATE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_LICENSING_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีความประสงค์จะเลิกกิจการสถานพยาบาล เนื่องจาก.
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_REASON {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ได้รับอนุญาตให้ประกอบกิจการสถานพยาบาลประเภท.
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รับผู้ป่วยไว้ค้างคืน.
        /// </summary>
        public static string APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_TYPE_TEXT {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_PERMISSION_CANCEL_INFO_SECTION_TYPE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่าเอกสารและข้อความข้างต้นเป็นความจริงทุกประการ.
        /// </summary>
        public static string HOSPITAL_TRUE {
            get {
                return ResourceManager.GetString("HOSPITAL_TRUE", resourceCulture);
            }
        }
    }
}
