//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESOURCE_APP_ACCOUNTING_SERVICE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCE_APP_ACCOUNTING_SERVICE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.RESOURCE_APP_ACCOUNTING_SERVICE", typeof(RESOURCE_APP_ACCOUNTING_SERVICE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการขอจดทะเบียนนิติบุคคลเพื่อประกอบกิจการให้บริการด้านวิชาชีพบัญชี.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลรายนามผู้ทำบัญชีที่รับผิดชอบในฐานะผู้ทำบัญชีของนิติบุคคล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลรายนามผู้ทำบัญชีที่รับผิดชอบในฐานะผู้ทำบัญชีของนิติบุคคล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_ADD {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขทะเบียนผู้สอบบัญชีรับอนุญาต.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_AUDITOR_ID {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_AUDITOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;ไม่มีข้อมูล ข้อมูลรายนามผู้ทำบัญชีที่รับผิดชอบในฐานะผู้ทำบัญชีของนิติบุคคล
        /// ในขณะนี้ คุณสามารถเพิ่มข้อมูลข้อมูลรายนามผู้ทำบัญชีที่รับผิดชอบในฐานะผู้ทำบัญชีของนิติบุคคล
        ///&lt;/div&gt;
        ///&lt;div&gt;โดยคลิกที่ปุ่ม&quot;เพิ่มข้อมูลรายนามผู้ทำบัญชีที่รับผิดชอบในฐานะผู้ทำบัญชีของนิติบุคคล
        ///&quot;&lt;/div&gt;.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_EMPTY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_FIRSTNAME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน 13 หลัก.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_ID {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_LASTNAME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลรายนามผู้ทำบัญชีที่รับผิดชอบในฐานะผู้ทำบัญชีของนิติบุคคล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_SUBMIT {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้าชื่อ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TITLE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทสมาชิก.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกสมทบ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TYPE_ASSOCIATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TYPE_ASSOCIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกวิสามัญ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TYPE_EXTRA_ORDIANY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TYPE_EXTRA_ORDIANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกสามัญ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TYPE_ORDIANRY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_TYPE_ORDIANRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระค่าบำรุงสมาชิกถึงวันที่.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_VAT_DATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_VAT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบปฏิบัติงาน.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_WORKING_TYPE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_WORKING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เต็มเวลา.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_WORKING_TYPE_FULLTIME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_WORKING_TYPE_FULLTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บางเวลา.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_WORKING_TYPE_PARTTIME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_ACCOUTANT_SECTION_WORKING_TYPE_PARTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลรายนามผู้สอบบัญชีรับอนุญาตที่ลงลายมือชื่อในฐานะผู้สอบบัญชีของนิติบุคคล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลรายนามผู้สอบบัญชีรับอนุญาตที่ลงลายมือชื่อในฐานะผู้สอบบัญชีของนิติบุคคล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_ADD {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขทะเบียนผู้สอบบัญชีรับอนุญาต.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_AUDITOR_ID {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_AUDITOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;ไม่มีข้อมูล ข้อมูลรายนามผู้สอบบัญชีรับอนุญาตที่ลงลายมือชื่อในฐานะผู้สอบบัญชีของนิติบุคคล
        /// ในขณะนี้ คุณสามารถเพิ่มข้อมูลข้อมูลรายนามผู้สอบบัญชีรับอนุญาตที่ลงลายมือชื่อในฐานะผู้สอบบัญชีของนิติบุคคล
        ///&lt;/div&gt;
        ///&lt;div&gt;โดยคลิกที่ปุ่ม&quot;เพิ่มข้อมูลรายนามผู้สอบบัญชีรับอนุญาตที่ลงลายมือชื่อในฐานะผู้สอบบัญชีของนิติบุคคล
        ///&quot;&lt;/div&gt;.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_EMPTY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_FIRSTNAME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน 13 หลัก.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_ID {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_LASTNAME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลรายนามผู้สอบบัญชีรับอนุญาตที่ลงลายมือชื่อในฐานะผู้สอบบัญชีของนิติบุคคล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_SUBMIT {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้าชื่อ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TITLE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทสมาชิก.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกสมทบ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TYPE_ASSOCIATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TYPE_ASSOCIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกวิสามัญ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TYPE_EXTRA_ORDIANY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TYPE_EXTRA_ORDIANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกสามัญ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TYPE_ORDIANRY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_TYPE_ORDIANRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระค่าบำรุงสมาชิกถึงวันที่.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_VAT_DATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_VAT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบปฏิบัติงาน.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_WORKING_TYPE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_WORKING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เต็มเวลา.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_WORKING_TYPE_FULLTIME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_WORKING_TYPE_FULLTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บางเวลา.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_WORKING_TYPE_PARTTIME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_AUDITOR_SECTION_WORKING_TYPE_PARTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลกิจการ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุวันที่จดทะเบียนเปลี่ยนแปลงวัตถุประสงค์เพื่อให้บริการด้านการสอบบัญชีหรือด้านการทำบัญชี.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_CHANGE_DATE_OPTION {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_CHANGE_DATE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลกรรมการผู้มีอำนาจลงนามผูกพันนิติบุคคลที่เป็นผู้ลงนามในการขออนุญาตครั้งนี้.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลของกรรมการผู้มีอำนาจลงนามที่มีเลขทะเบียนผู้สอบบัญชีรับอนุญาตให้ครบถ้วน.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE_FULL_VALIDATE_EXCEED {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE_FULL_VALIDATE_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรณีให้บริการประเภทสอบบัญชีหรือทำและสอบบัญชี กรรมการผู้มีอำนาจลงนามอย่างน้อย 1 คนต้องมีเลขทะเบียนผู้สอบบัญชีรับอนุญาต.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE_INFO {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขทะเบียนผู้สอบบัญชีรับอนุญาตสามารถกรอกได้ไม่เกิน 5 ตัวเลข.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE_LICENSE_VALIDATE_EXCEED {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE_LICENSE_VALIDATE_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรรมการผู้มีอำนาจลงนามอย่างน้อย 1 คน ต้องมีเลขทะเบียนผู้สอบบัญชีรับอนุญาต.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE_VALIDATE_EXCEED {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_COMMITTEE_VALIDATE_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลกิจการ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_CONFIRM {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้ารับรองว่า.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_CONFIRM_CONFIRM {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_CONFIRM_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;row&quot;&gt;
        ///&lt;div class=&quot;col-xs-12&quot;&gt;1. หลักฐานการขึ้นทะเบียนนิติบุคคล (พร้อมรับรองสำเนาถูกต้อง)&lt;/div&gt;
        ///&lt;div class=&quot;col-xs-11&quot; style=&quot;padding: 0px&quot;&gt;๐ หนังสือรับรองการจดทะเบียนนิติบุคคล ไม่เกิน 3 เดือน&lt;/div&gt;
        ///&lt;div class=&quot;col-xs-11&quot; style=&quot;padding: 0px&quot;&gt;๐ ข้อมูลในงบกำไรขาดทุน หรือสำเนางบการเงิน ย้อนหลัง 1 ปี (ถ้ามี) กรณีเป็นนิติบุคคลที่จดทะเบียนกับสภาวิชาชีพบัญชี ในพระบรมราชูปถัมภ์ครั้งแรก&lt;/div&gt;
        ///&lt;div class=&quot;col-xs-11&quot; style=&quot;padding: 0px&quot;&gt;๐ สำเนาบัตรประจำตัวประชาชนของกรรมการ/หุ้นส่วนผู้จัดการผู้มีอำนาจล [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_CONFIRM_CONFIRM_INFO {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_CONFIRM_CONFIRM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ขอจดทะเบียนนิติบุคคลต่อสภาวิชาชีพบัญชี ในพระบรมราชูปถัมภ์ภายใน 30 วันนับจาก.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่จดทะเบียนเปลี่ยนแปลงวัตถุประสงค์เพื่อให้บริการด้านการสอบบัญชีหรือด้านการทำบัญชี.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION_CHANGE_DATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION_CHANGE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่อื่นๆ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION_OTHER_DATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION_OTHER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่จดทะเบียนจัดตั้งนิติบุคคล .
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION_REGISTER_DATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่มประกอบธุรกิจให้บริการด้านการสอบบัญชีหรือด้านการทำบัญชี .
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION_START_DATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_OPTION_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุวันที่อื่นๆ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_OTHER_DATE_OPTION {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_OTHER_DATE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงินทุนจดทะเบียน (บาท).
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_REGISTER_CAPITAL {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_REGISTER_CAPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุวันที่จดทะเบียนจัดตั้งนิติบุคคล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_REGISTER_DATE_OPTION {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_REGISTER_DATE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุวันที่เริ่มประกอบธุรกิจให้บริการด้านการสอบบัญชีหรือด้านการทำบัญชี.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_START_DATE_OPTION {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_START_DATE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทของการให้บริการ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำบัญชี.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE_ACCOUNTING {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE_ACCOUNTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สอบบัญชี.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE_AUDITORING {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE_AUDITORING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทำบัญชีและสอบบัญชี.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE_BOTH {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE_BOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรณีให้บริการประเภทสอบบัญชีหรือทำและสอบบัญชี กรรมการผู้มีอำนาจลงนามอย่างน้อย 1 คน ต้องมีเลขทะเบียนผู้สอบบัญชีรับอนุญาต.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE_INVALID_LICENSE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_INFO_SECTION_TYPE_INVALID_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลหัวหน้าสำนักงาน.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_ADD {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขทะเบียนผู้สอบบัญชีรับอนุญาต.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_AUDITOR_ID {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_AUDITOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;ไม่มีข้อมูล ข้อมูลหัวหน้าสำนักงาน ในขณะนี้ คุณสามารถเพิ่มข้อมูลข้อมูลหัวหน้าสำนักงาน&lt;/div&gt;
        ///&lt;div&gt;โดยคลิกที่ปุ่ม&quot;เพิ่มข้อมูลหัวหน้าสำนักงาน&quot;&lt;/div&gt;.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_EMPTY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_FIRSTNAME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลหัวหน้าสำนักงาน.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_FORM {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน 13 หลัก.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_ID {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_LASTNAME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญชาติ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_NATIONALITY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_NATIONALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่หนังสือเดินทาง.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_PASSPORT {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_PASSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มข้อมูลหัวหน้าสำนักงาน.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_SUBMIT {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้าชื่อ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TITLE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทสมาชิก.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกสมทบ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TYPE_ASSOCIATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TYPE_ASSOCIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกวิสามัญ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TYPE_EXTRA_ORDIANY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TYPE_EXTRA_ORDIANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมาชิกสามัญ.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TYPE_ORDIANRY {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_TYPE_ORDIANRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระค่าบำรุงสมาชิกถึงวันที่.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_VAT_DATE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_VAT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบปฏิบัติงาน.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_WORKING_TYPE {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_WORKING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เต็มเวลา.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_WORKING_TYPE_FULLTIME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_WORKING_TYPE_FULLTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บางเวลา.
        /// </summary>
        public static string APP_ACCOUNTING_SERVICE_MANAGER_SECTION_WORKING_TYPE_PARTTIME {
            get {
                return ResourceManager.GetString("APP_ACCOUNTING_SERVICE_MANAGER_SECTION_WORKING_TYPE_PARTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่าข้อมูลต่างๆ ที่ได้ยื่นต่อสภาวิชาชีพบัญชี ในพระบรมราชูปถัมภ์เป็นข้อมูลที่ถูกต้องครบถ้วน และข้าพเจ้ายินดีที่จะแสดงหลักฐานและข้อมูลอื่นใดที่เกี่ยวข้องกับการปฎิบัติงานของผู้สอบบัญชีในสังกัด รวมทั้งระบบควบคุมคุณภาพสำนักงาน และยินยอมให้ผู้ที่ได้รับมอบหมายจากสภาวิชาชีพบัญชี ในพระบรมราชูปถัมภ์ เข้าเยี่ยมและตรวจสอบระบบควบคุมคุณภาพสำนักงาน ตลอดจนเรียกข้าพเจ้ามาให้ถ้อยคำ หรือชี้แจง หรือ ทำคำชี้แจงเป็นหนังสือ หรือ ส่งมอบเอกสารหลักฐานอื่นใดที่เกี่ยวข้องกับการปฎิบัติงานสอบบัญชีของผู้สอบบัญชีในสังกัด แล [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
    }
}
