//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESOURCE_APP_CLINIC_LICENSE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCE_APP_CLINIC_LICENSE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.RESOURCE_APP_CLINIC_LICENSE", typeof(RESOURCE_APP_CLINIC_LICENSE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลคำขออนุญาตให้ประกอบกิจการสถานพยาบาล (ส.พ.5).
        /// </summary>
        public static string APP_CLINIC_LICENSE {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มรายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_ADD {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_DAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ศุกร์.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_FRIDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จันทร์.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_MONDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เสาร์.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_SATURDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาทิตย์.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_SUNDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พฤหัส.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_THURSDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อังคาร.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_TUESDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พุธ.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_WEDNESDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_DAY_WEDNESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;ไม่มีข้อมูล รายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ ในขณะนี้ คุณสามารถเพิ่มข้อมูลรายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ&lt;/div&gt;
        ///&lt;div&gt;โดยคลิกที่ปุ่ม&quot;เพิ่มรายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ&quot;&lt;/div&gt;.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EMPTY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ (ภาษาอังกฤษ).
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มรายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ (ภาษาอังกฤษ).
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_ADD {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_FRIDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_MONDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_SATURDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_SUNDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_THURSDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_TUESDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_WEDNESDAY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_DAY_EN_WEDNESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;ไม่มีข้อมูล รายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ (ภาษาอังกฤษ) ในขณะนี้ คุณสามารถเพิ่มข้อมูลรายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ (ภาษาอังกฤษ)&lt;/div&gt;
        ///&lt;div&gt;โดยคลิกที่ปุ่ม&quot;เพิ่มรายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ (ภาษาอังกฤษ)&quot;&lt;/div&gt;.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_EMPTY {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening time.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_START_TIME_EN {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_START_TIME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มรายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ (ภาษาอังกฤษ).
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_SUBMIT {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing time.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_EN_TIME_OUT_EN {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_EN_TIME_OUT_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาเริ่มงาน.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_START_TIME {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มรายละเอียดวัน/เวลาที่ขออนุญาตประกอบกิจการ.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_SUBMIT {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาเลิกงาน.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_TIME_OUT {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_TIME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาเลิกงานต้องมากกว่าเวลาเริ่มงาน.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_TIME_OUT_INVALID {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_TIME_OUT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ช่วงเวลาทำงานนี้ซ้อนทับกับที่มีอยู่แล้ว.
        /// </summary>
        public static string APP_CLINIC_LICENSE_DETAIL_SECTION_TIME_OVERLAPPED {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_DETAIL_SECTION_TIME_OVERLAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลกิจการ.
        /// </summary>
        public static string APP_CLINIC_LICENSE_INFO_SECTION {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_INFO_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลกิจการ.
        /// </summary>
        public static string APP_CLINIC_LICENSE_INFO_SECTION_2 {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_INFO_SECTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่า.
        /// </summary>
        public static string APP_CLINIC_LICENSE_INFO_SECTION_2_CONFIRM_INFO_TRUE {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_INFO_SECTION_2_CONFIRM_INFO_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่า&lt;br/&gt;
        ///1.ไม่เคยได้รับโทษจำคุกโดยคำพิพากษาถึงที่สุดหรือคำสั่งที่ชอบด้วยกฎหมายถึงที่สุดให้จำคุก เว้นแต่เป็นโทษสำหรับความผิดที่กระทำโดยประมาทหรือความผิดลหุโทษ&lt;br/&gt;
        ///2.ไม่เป็นโรคตามที่รัฐมนตรีประกาศกำหนดโดยประกาศในราชกิจจานุเบกษา&lt;br/&gt;
        ///3.ไม่เป็นบุคคลล้มละลาย&lt;br/&gt;
        ///4.ไม่เป็นบุคคลวิกลจริต คนไร้ความสามารถ หรือคนเสมือนไร้ความสามารถ&lt;br/&gt;
        ///พร้อมกับคำขอนี้ข้าพเจ้าได้แนบเอกสารหลักฐานต่างๆมาด้วย คือ&lt;br/&gt;
        ///1.หนังสืออนุมัติแผนงานการจัดตั้งสถานพยาบาล&lt;br/&gt;
        ///2.แผนที่แสดงที่ตั้งของสถานพยาบาลและสิ่งปลูกสร้าง [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APP_CLINIC_LICENSE_INFO_SECTION_2_CONFIRM_INFO_TRUE_INFO {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_INFO_SECTION_2_CONFIRM_INFO_TRUE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอรับใบอนุญาตให้ประกอบกิจการสถานพยาบาลประเภทที่.
        /// </summary>
        public static string APP_CLINIC_LICENSE_INFO_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_INFO_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่รับผู้ป่วยค้างคืน.
        /// </summary>
        public static string APP_CLINIC_LICENSE_INFO_SECTION_TYPE_TEXT {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_INFO_SECTION_TYPE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบอนุญาตเดิม.
        /// </summary>
        public static string APP_CLINIC_LICENSE_OLD_INFO_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_CLINIC_LICENSE_OLD_INFO_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่าเอกสารและข้อความข้างต้นเป็นความจริงทุกประการ.
        /// </summary>
        public static string INFO_CHECKED_TRUE {
            get {
                return ResourceManager.GetString("INFO_CHECKED_TRUE", resourceCulture);
            }
        }
    }
}
