//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESOURCE_APP_HOSPITAL_LICENSE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCE_APP_HOSPITAL_LICENSE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.RESOURCE_APP_HOSPITAL_LICENSE", typeof(RESOURCE_APP_HOSPITAL_LICENSE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่าเอกสารและข้อความข้างต้นเป็นความจริงทุกประการ.
        /// </summary>
        public static string APP_HOSPITAL_CONFIRM_TRUE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_CONFIRM_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลคำขออนุมัติแผนงานการจัดตั้งสถานพยาบาลประเภทที่รับผู้ป่วยไว้ค้างคืน (ส.พ.3).
        /// </summary>
        public static string APP_HOSPITAL_LICENSE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลกิจการ.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดสถานพยาบาล.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_BED_AMOUNT {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_BED_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุ.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลผู้ป่วยเรื้อรัง.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_CHRONIC_PATIENTS {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_CHRONIC_PATIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลบำบัดยาเสพติด.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_DRUG_TREATMENT {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_DRUG_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลผู้สูงอายุ.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_ELDERLY {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_ELDERLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลแม่และเด็ก.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_MOTHER_CHILD {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_MOTHER_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะประเภทผู้ป่วยอื่นๆ.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_OTHER_PATIENTS {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_OTHER_PATIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลผู้ป่วยจิตเวช.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_PSYCHIATRIC {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_PSYCHIATRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะประเภทผู้ป่วย.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_SPECIFIC_PATIENT {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CHOICE_SPECIFIC_PATIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่า.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CONFIRM {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.ไม่เคยได้รับโทษจำคุกโดยคำพิพากษาถึงที่สุดหรือคำสั่งที่ชอบด้วยกฎหมายถึงที่สุดให้จำคุก เว้นแต่เป็นโทษสำหรับความผิดที่กระทำโดยประมาทหรือความผิดลหุโทษ&lt;/br&gt;
        ///2.ไม่เป็นโรคตามที่รัฐมนตรีประกาศกำหนดโดยประกาศในราชกิจจานุเบกษา&lt;/br&gt;
        ///3.ไม่เป็นบุคคลล้มละลาย&lt;/br&gt;
        ///4.ไม่เป็นบุคคลวิกลจริต คนไร้ความสามารถ หรือคนเสมือนไร้ความสามารถ&lt;/br&gt;&lt;/br&gt;
        ///พร้อมกับคำขอนี้ข้าพเจ้าได้แนบเอกสำรหลักฐานต่างๆมาด้วย คือ &lt;/br&gt;
        ///1.แผนงานการจัดตั้งสถานพยาบาลแผนงานการจัดตั้งสถานพยาบาล&lt;/br&gt;
        ///2.แผนที่แสดงที่ตั้งของสถานพยาบาลและสิ่งปลูกสร้างในบริเวณ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CONFIRM_INFO {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_CONFIRM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบุ.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TEXT {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานพยาบาลมีลักษณะเป็น.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลทันตกรรม.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_DENTAL_HOSPITAL {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_DENTAL_HOSPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลทั่วไป.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_GENERAL_HOSPITAL {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_GENERAL_HOSPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลการพยาบาลและการผดุงครรภ์.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_MIDWIFERY_HOSPITAL {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_MIDWIFERY_HOSPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลกายภาพบำบัด.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_PHYSICAL_THERAPY {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_PHYSICAL_THERAPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะทางโรคมะเร็ง.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIALIZED_CANCER {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIALIZED_CANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะทาง หู คอ จมูก.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIALIZED_EAR {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIALIZED_EAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะทาง โรคหัวใจ.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIALIZED_HEART_DISEASE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIALIZED_HEART_DISEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะทางอื่นๆ.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIALIZED_OTHER {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIALIZED_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลเฉพาะประเภทผู้ป่วย.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIFIC_PATIENT {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_SPECIFIC_PATIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลการแพทย์แผนไทย.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_THAI_TRADITIONAL {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_THAI_TRADITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โรงพยาบาลการแพทย์แผนไทยประยุกต์.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_THAI_TRADITIONAL_APPLIED {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_HOSPITAL_TYPE_THAI_TRADITIONAL_APPLIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขออนุมัติแผนงานการจัดตั้งสถานพยาบาลประเภทที่รับผู้ป่วยไว้ค้างคืน.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_SECTION_LICENSE {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_SECTION_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเตียง.
        /// </summary>
        public static string APP_HOSPITAL_LICENSE_INFO_TOTAL_BED {
            get {
                return ResourceManager.GetString("APP_HOSPITAL_LICENSE_INFO_TOTAL_BED", resourceCulture);
            }
        }
    }
}
