//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources.PermitResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESOURCE_APP_CLINIC_PLAN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESOURCE_APP_CLINIC_PLAN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitResource.RESOURCE_APP_CLINIC_PLAN", typeof(RESOURCE_APP_CLINIC_PLAN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ห้องฝังเข็ม.
        /// </summary>
        public static string ACUPUNCTURE_ROOM {
            get {
                return ResourceManager.GetString("ACUPUNCTURE_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลแผนการจัดตั้งสถานพยาบาลประเภทไม่รับผู้ป่วยค้างคืน (ส.พ.2).
        /// </summary>
        public static string APP_CLINIC_PLAN {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลกิจการ.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พื้นที่ (ตารางเมตร).
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_AREA {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคูหา.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_BOOTHS {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_BOOTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรณีที่ไม่มีคูหาให้ใส่ &quot;0&quot;.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_BOOTHS_INFO {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_BOOTHS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้ารับรองว่า.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_CONFIRM {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนชั้น.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_FLOORS {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_FLOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรณีเป็นอาคารชั้นเดียวให้กรอก 1 ชั้น.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_FLOORS_INFO {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_FLOORS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สูง (เมตร).
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_HIGH {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยาว (เมตร).
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_LENGTH {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนของผู้ประกอบวิชาชีพ (คน).
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_PROFESSIONALS {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_PROFESSIONALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการที่จัดให้มีเพิ่มเติม.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_SERVICES {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่นๆ.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_SERVICES_OTHER_TEXT {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_SERVICES_OTHER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลักษณะอาคารซึ่งใช้เป็นที่ตั้งสถานพยาบาล.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาคารพาณิชย์.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_COMMERCIAL_BUILDING {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_COMMERCIAL_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาคารสถานพยาบาลโดยเฉพาะ.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_HOSPITAL_BUILDINGS {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_HOSPITAL_BUILDINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ห้องแถว.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_HOUSE {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาคารสำนักงาน.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_OFFICE_BUILDING {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_OFFICE_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่นๆ.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_OTHER {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาคารที่อยู่อาศัย.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_RESIDENTIAL_BUILDING {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_RESIDENTIAL_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บ้านแถว.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_ROW_HOUSE {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_ROW_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งอยู่ในศูนย์การค้า.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_SHOPPING_CENTER {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_SHOPPING_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตึกแถว.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_TENEMENT_HOUSE {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_TENEMENT_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บ้านแฝด.
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_TYPE_TWIN_HOUSE {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_TYPE_TWIN_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กว้าง (เมตร).
        /// </summary>
        public static string APP_CLINIC_PLAN_INFO_SECTION_WIDTH {
            get {
                return ResourceManager.GetString("APP_CLINIC_PLAN_INFO_SECTION_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ห้องไตเทียม.
        /// </summary>
        public static string ARTIFICIAL_ROOM {
            get {
                return ResourceManager.GetString("ARTIFICIAL_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ห้องผ่าตัดใหญ่.
        /// </summary>
        public static string MAJOR_ROOM {
            get {
                return ResourceManager.GetString("MAJOR_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่นๆ.
        /// </summary>
        public static string OTHER {
            get {
                return ResourceManager.GetString("OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ห้องผ่าตัดเล็ก.
        /// </summary>
        public static string SMALL_ROOM {
            get {
                return ResourceManager.GetString("SMALL_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้าพเจ้าขอรับรองว่าเอกสารและข้อความข้างต้นเป็นความจริงทุกประการ.
        /// </summary>
        public static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ห้องเอกซเรย์.
        /// </summary>
        public static string XRAY_ROOM {
            get {
                return ResourceManager.GetString("XRAY_ROOM", resourceCulture);
            }
        }
    }
}
