//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Apps_EmployeeRegis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Apps_EmployeeRegis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.Apps_EmployeeRegis", typeof(Apps_EmployeeRegis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รองรับเอกสารชนิด pdf, png, jpg และมีขนาดของเอกสารไม่เกิน 5 เมกะไบต์.
        /// </summary>
        public static string APPS_ALLOWED_EXTENSIONS {
            get {
                return ResourceManager.GetString("APPS_ALLOWED_EXTENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหนังสือเดินทาง/สำเนาใบสำคัญประจำตัวคนต่างด้าว.
        /// </summary>
        public static string APPS_DOC_Passport {
            get {
                return ResourceManager.GetString("APPS_DOC_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหนังสือเดินทาง/สำเนาใบสำคัญประจำตัวคนต่างด้าว.
        /// </summary>
        public static string APPS_DOC_Passport_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_Passport_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนังสือนำส่งแบบขึ้นทะเบียนผู้ประกันตน สปส.1-03/สปส.1-03/1 (สปส.1-02).
        /// </summary>
        public static string APPS_DOC_RegistrationForm102 {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationForm102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนังสือนำส่งแบบขึ้นทะเบียนผู้ประกันตน สปส.1-03/สปส.1-03/1 (สปส.1-02).
        /// </summary>
        public static string APPS_DOC_RegistrationForm102_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationForm102_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบขึ้นทะเบียนผู้ประกันตน (สปส. 1-03).
        /// </summary>
        public static string APPS_DOC_RegistrationForm103 {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationForm103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบขึ้นทะเบียนผู้ประกันตน (สปส. 1-03).
        /// </summary>
        public static string APPS_DOC_RegistrationForm103_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationForm103_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สปส. 6-07.
        /// </summary>
        public static string APPS_DOC_RegistrationForm607 {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationForm607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สปส. 6-07.
        /// </summary>
        public static string APPS_DOC_RegistrationForm607_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationForm607_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาใบอนุญาติทำงานคนต่างด้าว.
        /// </summary>
        public static string APPS_DOC_WorkPermit {
            get {
                return ResourceManager.GetString("APPS_DOC_WorkPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาใบอนุญาติทำงานคนต่างด้าว.
        /// </summary>
        public static string APPS_DOC_WorkPermit_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_WorkPermit_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบรองรับเอกสารประเภท .pdf, .png และ .jpg เท่านั้น.
        /// </summary>
        public static string APPS_FILES_ERROR_EXTENSION {
            get {
                return ResourceManager.GetString("APPS_FILES_ERROR_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบรองรับเอกสารที่มีขนาดสูงสุดไม่เกิน 5 เมกะไบต์.
        /// </summary>
        public static string APPS_FILES_ERROR_SIZE {
            get {
                return ResourceManager.GetString("APPS_FILES_ERROR_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถอัปโหลดไฟล์เอกสารได้.
        /// </summary>
        public static string APPS_FILES_ERROR_UPLOAD_FAILED {
            get {
                return ResourceManager.GetString("APPS_FILES_ERROR_UPLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้นายจ้างแจ้งขึ้นทะเบียนผู้ประกันตนต่อสํานักงานประกันสังคมภายใน 30 วัน นับแต่วันที่รับลูกจ้าง เข้าทำงานมิฉะนั้นจะมีความผิดต้องระวางโทษจำคุกไม่เกิน 6เดือน หรือปรับไม่เกิน 20,000 บาท หรือ ทั้งจำทั้งปรับ
        ///                    โดยนายจ้างมีหน้าที่รวบรวมแบบขึ้นทะเบียนผู้ประกันตน (สปส. 1-03) โดยใช้แบบ สปส. 1-02 เป็นหนังสือนำส่งในการยื่นต่อสํานักงานประกันสังคม.
        /// </summary>
        public static string APPS_INTRO {
            get {
                return ResourceManager.GetString("APPS_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขึ้นทะเบียนผู้ประกันตน (สปส 1-03).
        /// </summary>
        public static string APPS_NAME {
            get {
                return ResourceManager.GetString("APPS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกเอกสาร หรือหากกำลังนำเอกสารเข้าสู่ระบบกรุณารอสักครู่.
        /// </summary>
        public static string APPS_SELECT_AND_WAIT {
            get {
                return ResourceManager.GetString("APPS_SELECT_AND_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขั้นตอนการขึ้นทะเบียนผู้ประกันตน (สปส 1-03).
        /// </summary>
        public static string APPS_STEP {
            get {
                return ResourceManager.GetString("APPS_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกแบบขึ้นทะเบียนผู้ประกันตน สปส. 1-03
        ///                                &lt;br /&gt;
        ///                                กรอกเอกสาร
        ///                                &lt;a target=&quot;_blank&quot; href=&quot;{0}&quot;&gt; [ดาวน์โหลดแบบฟอร์ม สปส.1-03 (1 ผู้ประกันตน ต่อเอกสาร 1 ชุด)] &lt;/a&gt; &amp;nbsp; &lt;a target=&quot;_blank&quot; href=&quot;{1}&quot;&gt;[ตัวอย่างการกรอกแบบฟอร์ม สปส.1-03] &lt;/a&gt;.
        /// </summary>
        public static string APPS_STEP_1 {
            get {
                return ResourceManager.GetString("APPS_STEP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เป็นคนไทยหรือไม่ ?.
        /// </summary>
        public static string APPS_STEP_1_ARE_YOU_THAI {
            get {
                return ResourceManager.GetString("APPS_STEP_1_ARE_YOU_THAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกเอกสาร.
        /// </summary>
        public static string APPS_STEP_1_CHOOSE_DOCUMENT {
            get {
                return ResourceManager.GetString("APPS_STEP_1_CHOOSE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขประจำตัวประชาชนประชาชน 13 หลัก.
        /// </summary>
        public static string APPS_STEP_1_CITIZEN_ID {
            get {
                return ResourceManager.GetString("APPS_STEP_1_CITIZEN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประชาชน 13 หลักไม่ถูกต้อง.
        /// </summary>
        public static string APPS_STEP_1_CITIZEN_ID_INVALID {
            get {
                return ResourceManager.GetString("APPS_STEP_1_CITIZEN_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุหมายเลขประจำตัวประชาชน 13 หลัก.
        /// </summary>
        public static string APPS_STEP_1_CITIZEN_ID_REQUIRED {
            get {
                return ResourceManager.GetString("APPS_STEP_1_CITIZEN_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ใช่.
        /// </summary>
        public static string APPS_STEP_1_NO {
            get {
                return ResourceManager.GetString("APPS_STEP_1_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขหนังสือเดินทาง.
        /// </summary>
        public static string APPS_STEP_1_PASSPORT_NUMBER {
            get {
                return ResourceManager.GetString("APPS_STEP_1_PASSPORT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุหมายเลขหนังสือเดินทาง.
        /// </summary>
        public static string APPS_STEP_1_PASSPORT_NUMBER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("APPS_STEP_1_PASSPORT_NUMBER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;หมายเหตุ&lt;/strong&gt; * กรุณาคลิก &quot;บันทึกข้อมูลผู้ประกันตน&quot; เพื่อบันทึกข้อมูลผู้ประกันตน(สปส. 1-03) เป็นรายบุคคล.
        /// </summary>
        public static string APPS_STEP_1_REMARK {
            get {
                return ResourceManager.GetString("APPS_STEP_1_REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช่.
        /// </summary>
        public static string APPS_STEP_1_YES {
            get {
                return ResourceManager.GetString("APPS_STEP_1_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้นายจ้างกรอกชื่อสถานประกอบการพร้อมเลขที่บัญชีและลําดับที่สาขา สถานที่ตั้งของสถานประกอบ การลงในหนังสือนําส่ง (สปส.1-02) พร้อมระบุจํานวน สปส.1-03 ที่นำส่ง กรณีเป็น สถานประกอบการสาขาให้แยก สปส. 1-03 ตามลำดับที่สาขาพร้อมทั้งทำหนังสือนำส่ง (สปส.1-02) เช่นดียวกัน &lt;br /&gt;
        ///                            &lt;span class=&quot;font-size-sm&quot;&gt;* หมายเหตุ ผู้ลงชื่อในหนังสือนําส่งแบบขึ้นทะเบียนผู้ประกันตน เป็นผู้มีอำนาจกระทำการผูกพันบริษัทหรือผู้ได้รับมอบอํานาจ &lt;/span&gt;
        ///                            &lt;br /&gt;
        ///                           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APPS_STEP_2_INTRO {
            get {
                return ResourceManager.GetString("APPS_STEP_2_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;หมายเหตุ&lt;/strong&gt; * เอกสารที่จำเป็นต้องส่ง.
        /// </summary>
        public static string APPS_STEP_2_REMARK {
            get {
                return ResourceManager.GetString("APPS_STEP_2_REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกเอกสาร.
        /// </summary>
        public static string APPS_STEP_2_SELECT_PAPERS {
            get {
                return ResourceManager.GetString("APPS_STEP_2_SELECT_PAPERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบเอกสาร.
        /// </summary>
        public static string APPS_STEP_3_CHECK_DOCUMENT {
            get {
                return ResourceManager.GetString("APPS_STEP_3_CHECK_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบความถูกต้องสมบูรณ์ของเอกสาร.
        /// </summary>
        public static string APPS_STEP_3_INTRO {
            get {
                return ResourceManager.GetString("APPS_STEP_3_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดูสถานะการขึ้นทะเบียนผู้ประกันตน (สปส 1-03).
        /// </summary>
        public static string APPS_TRACKING_YOUR_REQUEST {
            get {
                return ResourceManager.GetString("APPS_TRACKING_YOUR_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารแนบ.
        /// </summary>
        public static string ATTACHED_FILE {
            get {
                return ResourceManager.GetString("ATTACHED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลับไปยังหน้าจอขึ้นทะเบียนผู้ประกันตน (สปส 1-03).
        /// </summary>
        public static string BACK_TO_EMPLOYEE_APP {
            get {
                return ResourceManager.GetString("BACK_TO_EMPLOYEE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิด.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบ.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดแบบฟอร์ม สปส.1-02.
        /// </summary>
        public static string DOWNLOAD_SSO_102 {
            get {
                return ResourceManager.GetString("DOWNLOAD_SSO_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดแบบฟอร์ม สปส.1-03.
        /// </summary>
        public static string DOWNLOAD_SSO_103 {
            get {
                return ResourceManager.GetString("DOWNLOAD_SSO_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้ยื่นคำร้องการขึ้นทะเบียนผู้ประกันตน (สปส 1-03) และได้รับการอนุมัติเป็นที่เรียบร้อยแล้ว.
        /// </summary>
        public static string MSG_COMPLETED_REQ {
            get {
                return ResourceManager.GetString("MSG_COMPLETED_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้ยื่นคำร้องการขึ้นทะเบียนผู้ประกันตน (สปส 1-03) เป็นที่เรียบร้อยแล้ว กรุณารอการอนุมัติจากเจ้าหน้าที่.
        /// </summary>
        public static string MSG_PENDING_REQ {
            get {
                return ResourceManager.GetString("MSG_PENDING_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเข้าถึงบริการได้กรุณาติดต่อเจ้าหน้าที่.
        /// </summary>
        public static string MSG_UNKNOWN_STATUS {
            get {
                return ResourceManager.GetString("MSG_UNKNOWN_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาอัปโหลดไฟล์ในขั้นตอนที่ 1 และ 2 ให้ครบถ้วน.
        /// </summary>
        public static string PLEASE_UPLOAD_DOC_IN_STEP_1_2 {
            get {
                return ResourceManager.GetString("PLEASE_UPLOAD_DOC_IN_STEP_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบฟอร์มขึ้นทะเบียน.
        /// </summary>
        public static string REGISTRATION_FORM {
            get {
                return ResourceManager.GetString("REGISTRATION_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกแบบร่าง.
        /// </summary>
        public static string SAVE_DRAFT {
            get {
                return ResourceManager.GetString("SAVE_DRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกอีเมล์.
        /// </summary>
        public static string SUBMIT_EMAIL {
            get {
                return ResourceManager.GetString("SUBMIT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งคำร้อง.
        /// </summary>
        public static string SUBMIT_REQUEST {
            get {
                return ResourceManager.GetString("SUBMIT_REQUEST", resourceCulture);
            }
        }
    }
}
