//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Apps_SingleForm_Required {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Apps_SingleForm_Required() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.Apps_SingleForm_Required", typeof(Apps_SingleForm_Required).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดยอมรับ.
        /// </summary>
        public static string DANGER_FOOD_CONFIRM {
            get {
                return ResourceManager.GetString("DANGER_FOOD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดยอมรับ.
        /// </summary>
        public static string DIRECT_MARKETING_CONFIRM {
            get {
                return ResourceManager.GetString("DIRECT_MARKETING_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดยอมรับ.
        /// </summary>
        public static string DIRECT_MARKETING_WARNING_CONFIRM {
            get {
                return ResourceManager.GetString("DIRECT_MARKETING_WARNING_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดยอมรับ.
        /// </summary>
        public static string DIRECT_SELL_CONFIRM {
            get {
                return ResourceManager.GetString("DIRECT_SELL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดยอมรับ.
        /// </summary>
        public static string DIRECT_SELL_WARNING_CONFIRM {
            get {
                return ResourceManager.GetString("DIRECT_SELL_WARNING_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกรายรับต่อเดือนของสถานประกอบการโดยประมาณ (บาท).
        /// </summary>
        public static string MONTHLY_REVENUE {
            get {
                return ResourceManager.GetString("MONTHLY_REVENUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดยอมรับ.
        /// </summary>
        public static string SELL_ALCOHOL_CONFIRM {
            get {
                return ResourceManager.GetString("SELL_ALCOHOL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากดยอมรับ.
        /// </summary>
        public static string SELL_FOOD_CONFIRM {
            get {
                return ResourceManager.GetString("SELL_FOOD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณารับรองว่าข้อความในแบบคำขอที่ยื่นมานี้มีความถูกต้องและเป็นจริงทุกประการ.
        /// </summary>
        public static string SELL_TABACCO_CONFIRM {
            get {
                return ResourceManager.GetString("SELL_TABACCO_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกกรณีการจดทะเบียนภาษีมูลค่าเพิ่มที่ตรงกับเงื่อนไขของคุณ.
        /// </summary>
        public static string VAT_CONDITION {
            get {
                return ResourceManager.GetString("VAT_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกประเภทกิจการที่คุณต้องการจดทะเบียนภาษีมูลค่าเพิ่ม.
        /// </summary>
        public static string VAT_TYPE {
            get {
                return ResourceManager.GetString("VAT_TYPE", resourceCulture);
            }
        }
    }
}
