//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Apps_EmployerRegis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Apps_EmployerRegis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.Apps_EmployerRegis", typeof(Apps_EmployerRegis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รองรับเอกสารชนิด pdf, png, jpg และมีขนาดของเอกสารไม่เกิน 5 เมกะไบต์.
        /// </summary>
        public static string APPS_ALLOWED_EXTENSIONS {
            get {
                return ResourceManager.GetString("APPS_ALLOWED_EXTENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                    &lt;li&gt;
        ///                        นายจ้างที่มีลูกจ้างตั้งแต่ 1 คนขึ้นไป ต้องขึ้นทะเบียนนายจ้างพร้อมกับขึ้นทะเบียนลูกจ้าง เป็นผู้ประกันตน ภายใน 30 วัน และเมื่อมีการรับลูกจ้างใหม่เพิ่มขึ้นต้องแจ้งขึ้นทะเบียนลูกจ้างใหม่ภายใน 30 วัน เช่นกัน
        ///                    &lt;/li&gt;
        ///                    &lt;li&gt;
        ///                        ผู้ประกันตน คือ ลูกจ้างที่มีอายุไม่ต่ำกว่า 15 ปีบริบูรณ์ และไม่เกิน 60 ปีบริบูรณ์ในวันเข้าทำงาน  และทำงานอยู่ในสถานประกอบการที่มีลูกจ้างตั้งแต่ 1 คนขึ้นไป
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("APPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ๋ายบัตรประจําตัวประชาชน (คนต่างด้าวใช้สําเนาหนังสือเดินทางหรือใบสําคัญประจำตัวคนต่างด้าว).
        /// </summary>
        public static string APPS_DOC_CitizenCard {
            get {
                return ResourceManager.GetString("APPS_DOC_CitizenCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ๋ายบัตรประจําตัวประชาชน (คนต่างด้าวใช้สําเนาหนังสือเดินทางหรือใบสําคัญประจำตัวคนต่างด้าว).
        /// </summary>
        public static string APPS_DOC_CitizenCard_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_CitizenCard_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหนังสือสัญญาเช่า.
        /// </summary>
        public static string APPS_DOC_Contract {
            get {
                return ResourceManager.GetString("APPS_DOC_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหนังสือสัญญาเช่า หรือหนังสือยินยอมให้ใช้สถานที่พร้อมสำเนาบัตรประจำตัวประชาชนและสำเนาทะเบียนบ้านของผู้ให้เช่า หรือสัญญาเช่าแผง หรือหลักฐานแสดงเลขที่แผงและที่ตั้งของตลาด หรือห้างสรรพสินค้า.
        /// </summary>
        public static string APPS_DOC_Contract_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_Contract_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักฐานการแสดงตัวของนายจ้าง.
        /// </summary>
        public static string APPS_DOC_EmployerDoc {
            get {
                return ResourceManager.GetString("APPS_DOC_EmployerDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักฐานการแสดงตัวของนายจ้าง เช่น สำเนาบัตรประจำตัวประชาชน หรือสำเนาทะเบียนบ้านของนายจ้างหรือกรรมการผู้มีอำนาจลงนาม (กรณีกรรมการบริษัทเป็นชาวต่างชาติ ใช้สำเนาPASSPORT หรือWORK PERMIT หรือVISA)(คนต่างด้าวใช้สำเนาหนังสือเดินทาง หรือสำเนาใบสำคัญประจำตัวคนต่างด้าว) หรือสำเนาใบสำคัญถิ่นที่อยู่ในราชอาณาจักร หรือหลักฐานการได้รับอนุญาตให้เข้ามาในราชอาณาจักรเป็นการชั่วคราวตามกฎหมายว่าด้วยคนเข้ามืองของผู้มีอำนาจผูกพันนิติบุคคล เป็นต้น.
        /// </summary>
        public static string APPS_DOC_EmployerDoc_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_EmployerDoc_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แผนที่ตั้งและภาพถ่ายของสถานประกอบการ.
        /// </summary>
        public static string APPS_DOC_Map {
            get {
                return ResourceManager.GetString("APPS_DOC_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แผนที่ตั้งและภาพถ่ายของสถานประกอบการ.
        /// </summary>
        public static string APPS_DOC_Map_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_Map_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนังสือมอบอำนาจ.
        /// </summary>
        public static string APPS_DOC_PowerOfAttorney {
            get {
                return ResourceManager.GetString("APPS_DOC_PowerOfAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนังสือมอบอำนาจ (เฉพาะกรณีมอบอำนาจให้บุคคลอื่นกระทำการแทนพร้อมติดอากรแสตมป์ตามที่ประมวลรัษฎากรกำหนด) แนบสำเนาบัตรประจำตัวประชำชนของผู้มอบอำนาจและผู้รับมอบอำนาจ.
        /// </summary>
        public static string APPS_DOC_PowerOfAttorney_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_PowerOfAttorney_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ่ายทะเบียนบ้าน.
        /// </summary>
        public static string APPS_DOC_RegistrationBook {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ่ายทะเบียนบ้าน.
        /// </summary>
        public static string APPS_DOC_RegistrationBook_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationBook_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบขึ้นทะเบียนนายจ้าง (สปส.1-01).
        /// </summary>
        public static string APPS_DOC_RegistrationForm {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบขึ้นทะเบียนายจ้าง (สปส.1-01) &lt;br/&gt;  (ในกรณีที่เนื้อที่กรอกข้อมูลในแบบฟอร์มข้อ 2, ข้อ 3.2 และข้อ 6 ไม่เพียงพอ ขอให้ใช้กระดาษอื่นกรอกข้อมูลต่อไปจนครบ จากนั้นบันทึกไฟล์เอกสารและอัปโหลดเพิ่ม).
        /// </summary>
        public static string APPS_DOC_RegistrationForm_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationForm_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ่ายหนังสือรับรองการจดทะเบียนนิติบุคคลพร้อมวัตถุประสงค์.
        /// </summary>
        public static string APPS_DOC_RegistrationJuristic {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationJuristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหนังสือรับรองการจดทะเบียนนิติบุคคล พร้อมวัตถุประสงค์ หรือสำเนาใบทะเบียนพาณิชย์ หรือหนังสือรับรองตามพระราชบัญญัติประกอบธุรกิจคนต่างด้าว พ.ศ.2542 หรือสำเนาสัญญาร่วมค้า หรือสำเนาหนังสือรับรองแสดงการ จดทะเบียนนิติบุคคลของทุกรายที่ร่วมค้ำ หรือสำเนาหนังสือรับรองหรือหลักฐานการเป็นนิติบุคคลซึ่งแสดงรายการเกี่ยวกับชื่อ ทุน วัตถุประสงค์ รายชื่อกรรมการและผู้มีอำนาจลงนามผูกพันนิติบุคคล และหนังสือแต่งตั้งผู้แทนโดยผู้มีอำนาจลงนามผูกพันนิติบุคคลที่ขอจดทะเบียนนายจ้างเป็นผู้แต่งตั้งให้มีหน้าที่รับผิดชอบดำเนินกิจการในประ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APPS_DOC_RegistrationJuristic_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationJuristic_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหรือภาพถ่าย บัตรประจำตัวผู้เสียภาษีอากร/ร.ง. 4/ภ.พ.20/ภ.ธ. 20.
        /// </summary>
        public static string APPS_DOC_RegistrationPersonalVat {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationPersonalVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาบัตรประจำตัวผู้เสียภาษีอากร หรือสําเนาภาพถ่ายใบอนุญาตประกอบกิจการโรงงาน (ร.ง. 4) หรือสําเนาหรือภาพถ่ายใบทะเบียนภาษีมูลคาเพิ่ม (ภ.พ.20) หรือสําเนาภาพถ่ายภาษีธุรกิจเฉพาะ (ภ.ธ. 20).
        /// </summary>
        public static string APPS_DOC_RegistrationPersonalVat_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationPersonalVat_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหรือภาพถ่าย ภ.พ.01/ ภธ.20/ ใบอนุญาตประกอบธุรกิจของคนต่างด้าว.
        /// </summary>
        public static string APPS_DOC_RegistrationVat {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาบัตรประจำตัวผู้เสียภาษีอากร หรือสำเนาคำขอจดทะเบียนภาษีมูลค่าเพิ่ม (ภ.พ.01) หรือสำเนาภาษีธุรกิจเฉพาะ (ภธ.20) หรือใบอนุญาตประกอบธุรกิจของคนต่างด้าว.
        /// </summary>
        public static string APPS_DOC_RegistrationVat_DESC {
            get {
                return ResourceManager.GetString("APPS_DOC_RegistrationVat_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบรองรับเอกสารประเภท .pdf, .png และ .jpg เท่านั้น.
        /// </summary>
        public static string APPS_FILES_ERROR_EXTENSION {
            get {
                return ResourceManager.GetString("APPS_FILES_ERROR_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบรองรับเอกสารที่มีขนาดสูงสุดไม่เกิน 5 เมกะไบต์.
        /// </summary>
        public static string APPS_FILES_ERROR_SIZE {
            get {
                return ResourceManager.GetString("APPS_FILES_ERROR_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถอัปโหลดไฟล์เอกสารได้.
        /// </summary>
        public static string APPS_FILES_ERROR_UPLOAD_FAILED {
            get {
                return ResourceManager.GetString("APPS_FILES_ERROR_UPLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        public static string APPS_MSG_CANCEL {
            get {
                return ResourceManager.GetString("APPS_MSG_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาด ไม่บันทึกฉบับร่างได้กรุณาลองใหม่อีกครั้ง.
        /// </summary>
        public static string APPS_MSG_DRAFT_ERROR_TRY_AGAIN {
            get {
                return ResourceManager.GetString("APPS_MSG_DRAFT_ERROR_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกแบบร่าง.
        /// </summary>
        public static string APPS_MSG_DRAFT_TITLE {
            get {
                return ResourceManager.GetString("APPS_MSG_DRAFT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกอีเมล์.
        /// </summary>
        public static string APPS_MSG_ENTER_EMAIL {
            get {
                return ResourceManager.GetString("APPS_MSG_ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาด ไม่สามารถยื่นคำร้องได้กรุณาลองใหม่อีกครั้ง.
        /// </summary>
        public static string APPS_MSG_ERROR_TRY_AGAIN {
            get {
                return ResourceManager.GetString("APPS_MSG_ERROR_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาอัปโหลดไฟล์เอกสารที่จำเป็นให้ครบถ้วน.
        /// </summary>
        public static string APPS_MSG_FILES_REQUIRED {
            get {
                return ResourceManager.GetString("APPS_MSG_FILES_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งคำร้อง.
        /// </summary>
        public static string APPS_MSG_TITLE {
            get {
                return ResourceManager.GetString("APPS_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขึ้นทะเบียนนายจ้าง.
        /// </summary>
        public static string APPS_NAME {
            get {
                return ResourceManager.GetString("APPS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกเอกสาร หรือหากกำลังนำเอกสารเข้าสู่ระบบกรุณารอสักครู่.
        /// </summary>
        public static string APPS_SELECT_AND_WAIT {
            get {
                return ResourceManager.GetString("APPS_SELECT_AND_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรอกและยื่นเอกสารแบบฟอร์มขึ้นทะเบียนนายจ้างล่วงหน้า ผ่านระบบอินเตอร์เน็ต.
        /// </summary>
        public static string APPS_STEP_1 {
            get {
                return ResourceManager.GetString("APPS_STEP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ดาวน์โหลดแบบฟอร์มขึ้นทะเบียนนายจ้าง].
        /// </summary>
        public static string APPS_STEP_1_DL {
            get {
                return ResourceManager.GetString("APPS_STEP_1_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ตัวอย่างการกรอกแบบฟอร์มขึ้นทะเบียนนายจ้าง].
        /// </summary>
        public static string APPS_STEP_1_DL_EX {
            get {
                return ResourceManager.GetString("APPS_STEP_1_DL_EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัปโหลดส่งแบบฟอร์มขึ้นทะเบียนนายจ้างและเอกสารที่เกี่ยวข้อง.
        /// </summary>
        public static string APPS_STEP_2 {
            get {
                return ResourceManager.GetString("APPS_STEP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกเอกสาร.
        /// </summary>
        public static string APPS_STEP_2_PANEL_HEADER {
            get {
                return ResourceManager.GetString("APPS_STEP_2_PANEL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;หมายเหตุ&lt;/strong&gt; * เอกสารที่จำเป็นต้องส่ง.
        /// </summary>
        public static string APPS_STEP_2_REMARK {
            get {
                return ResourceManager.GetString("APPS_STEP_2_REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบความถูกต้องสมบูรณ์ของเอกสาร.
        /// </summary>
        public static string APPS_STEP_3 {
            get {
                return ResourceManager.GetString("APPS_STEP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบเอกสาร.
        /// </summary>
        public static string APPS_STEP_3_PANEL_HEADER {
            get {
                return ResourceManager.GetString("APPS_STEP_3_PANEL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;หมายเหตุ&lt;/strong&gt; เมื่อท่านได้รับการอนุมัติแล้ว  ในการติดต่อสำนักงานฯ ขอให้ท่านแจ้งเลขที่บัญชีดังกล่าวทุกครั้ง  และขอเรียนชี้แจงเพิ่มเติมดังนี้&lt;/p&gt;
        ///                &lt;ol&gt;
        ///                    &lt;li&gt;
        ///                        &lt;p&gt;
        ///                            กองทุนเงินทดแทน  ให้ความคุ้มครองแก่ลูกจ้างที่ประสบอันตราย  เจ็บป่วย  ทุพพลภาพ
        ///                            หรือตาย  อันเนื่องจากการทำงานให้นายจ้าง  โดยนายจ้างเป็นผู้จ่ายเงินสมทบฝ่ายเดียว  ปีละ  1  ครั้ง ทั้งนี้ สำนักงานประกันสังคมจะส่งใบประเมินเงิ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APPS_STEP_3_REMARK {
            get {
                return ResourceManager.GetString("APPS_STEP_3_REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขั้นตอนการขึ้นทะเบียนนายจ้าง.
        /// </summary>
        public static string APPS_STEPS {
            get {
                return ResourceManager.GetString("APPS_STEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดูสถานะการขึ้นทะเบียนนายจ้าง.
        /// </summary>
        public static string APPS_TRACKING_YOUR_REQUEST {
            get {
                return ResourceManager.GetString("APPS_TRACKING_YOUR_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารแนบ.
        /// </summary>
        public static string ATTACHED_FILE {
            get {
                return ResourceManager.GetString("ATTACHED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลับไปยังหน้าจอขึ้นทะเบียนนายจ้าง.
        /// </summary>
        public static string BACK_TO_EMPLOYER_REGIS_APP {
            get {
                return ResourceManager.GetString("BACK_TO_EMPLOYER_REGIS_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบ.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดแบบฟอร์มขึ้นทะเบียนนายจ้าง.
        /// </summary>
        public static string DOWNLOAD_EMPLOYER_REGIS_FORM {
            get {
                return ResourceManager.GetString("DOWNLOAD_EMPLOYER_REGIS_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้ยื่นคำร้องการขึ้นทะเบียนนายจ้าง และได้รับการอนุมัติเป็นที่เรียบร้อยแล้ว.
        /// </summary>
        public static string MSG_COMPLETED_REQ {
            get {
                return ResourceManager.GetString("MSG_COMPLETED_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้ยื่นคำร้องการขึ้นทะเบียนนายจ้างเป็นที่เรียบร้อยแล้ว กรุณารอการอนุมัติจากเจ้าหน้าที่.
        /// </summary>
        public static string MSG_PENDING_REQ {
            get {
                return ResourceManager.GetString("MSG_PENDING_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเข้าถึงบริการได้กรุณาติดต่อเจ้าหน้าที่.
        /// </summary>
        public static string MSG_UNKNOWN_STATUS {
            get {
                return ResourceManager.GetString("MSG_UNKNOWN_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านได้ยื่นคำร้องการขึ้นทะเบียนนายจ้างเป็นที่เรียบร้อยแล้ว กรุณารอการตอบรับจากเจ้าหน้าที่.
        /// </summary>
        public static string MSG_WAITING_REQ {
            get {
                return ResourceManager.GetString("MSG_WAITING_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบฟอร์มขึ้นทะเบียน.
        /// </summary>
        public static string REGISTRATION_FORM {
            get {
                return ResourceManager.GetString("REGISTRATION_FORM", resourceCulture);
            }
        }
    }
}
