//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Apps_Utility {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Apps_Utility() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.Apps_Utility", typeof(Apps_Utility).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อำเภอ/เขต.
        /// </summary>
        public static string ADDRESS_AMPHUR {
            get {
                return ResourceManager.GetString("ADDRESS_AMPHUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาคาร.
        /// </summary>
        public static string ADDRESS_BUILDING {
            get {
                return ResourceManager.GetString("ADDRESS_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่ออาคาร/หมู่บ้าน.
        /// </summary>
        public static string ADDRESS_BUILDING_VILLAGE {
            get {
                return ResourceManager.GetString("ADDRESS_BUILDING_VILLAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกอำเภอ.
        /// </summary>
        public static string ADDRESS_CHOOSE_AMPHUR {
            get {
                return ResourceManager.GetString("ADDRESS_CHOOSE_AMPHUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกจังหวัด.
        /// </summary>
        public static string ADDRESS_CHOOSE_PROVINCE {
            get {
                return ResourceManager.GetString("ADDRESS_CHOOSE_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกตำบล.
        /// </summary>
        public static string ADDRESS_CHOOSE_TAMBOL {
            get {
                return ResourceManager.GetString("ADDRESS_CHOOSE_TAMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรสาร.
        /// </summary>
        public static string ADDRESS_FAX {
            get {
                return ResourceManager.GetString("ADDRESS_FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชั้น.
        /// </summary>
        public static string ADDRESS_FLOOR {
            get {
                return ResourceManager.GetString("ADDRESS_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสประจำบ้านตามทะเบียนบ้าน 11 หลัก.
        /// </summary>
        public static string ADDRESS_HOUSE_REG_ID {
            get {
                return ResourceManager.GetString("ADDRESS_HOUSE_REG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกสถานที่ขอติดตั้ง.
        /// </summary>
        public static string ADDRESS_INFORMATION {
            get {
                return ResourceManager.GetString("ADDRESS_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ละติจูด.
        /// </summary>
        public static string ADDRESS_LAT {
            get {
                return ResourceManager.GetString("ADDRESS_LAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลองจิจูด.
        /// </summary>
        public static string ADDRESS_LNG {
            get {
                return ResourceManager.GetString("ADDRESS_LNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมู่.
        /// </summary>
        public static string ADDRESS_MOO {
            get {
                return ResourceManager.GetString("ADDRESS_MOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บ้านเลขที่.
        /// </summary>
        public static string ADDRESS_NUMBER {
            get {
                return ResourceManager.GetString("ADDRESS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จังหวัด.
        /// </summary>
        public static string ADDRESS_PROVINCE {
            get {
                return ResourceManager.GetString("ADDRESS_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ซอย.
        /// </summary>
        public static string ADDRESS_SOI {
            get {
                return ResourceManager.GetString("ADDRESS_SOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถนน.
        /// </summary>
        public static string ADDRESS_STREET {
            get {
                return ResourceManager.GetString("ADDRESS_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำบล/แขวง.
        /// </summary>
        public static string ADDRESS_TAMBOL {
            get {
                return ResourceManager.GetString("ADDRESS_TAMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์.
        /// </summary>
        public static string ADDRESS_TEL {
            get {
                return ResourceManager.GetString("ADDRESS_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต่อ.
        /// </summary>
        public static string ADDRESS_TEL_EXT {
            get {
                return ResourceManager.GetString("ADDRESS_TEL_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมู่บ้าน.
        /// </summary>
        public static string ADDRESS_VILLAGE {
            get {
                return ResourceManager.GetString("ADDRESS_VILLAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์.
        /// </summary>
        public static string ADDRESS_ZIP_CODE {
            get {
                return ResourceManager.GetString("ADDRESS_ZIP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบข้อมูลอีกครั้ง.
        /// </summary>
        public static string ALERT_CANCEL_BTN {
            get {
                return ResourceManager.GetString("ALERT_CANCEL_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งข้อมูล.
        /// </summary>
        public static string ALERT_CONFIRM_BTN {
            get {
                return ResourceManager.GetString("ALERT_CONFIRM_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบข้อมูลให้ถูกต้องก่อนส่งข้อมูล.
        /// </summary>
        public static string ALERT_CONFIRM_DESC {
            get {
                return ResourceManager.GetString("ALERT_CONFIRM_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการส่งข้อมูล.
        /// </summary>
        public static string ALERT_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("ALERT_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แนบสำเนาบัตรประชาชน.
        /// </summary>
        public static string APPS_ATTACH_COPY_OF_CITIZEN_CARD {
            get {
                return ResourceManager.GetString("APPS_ATTACH_COPY_OF_CITIZEN_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รองรับเอกสารชนิด pdf, png, jpg ที่มีขนาดไม่เกิน 5 MB เท่านั้น.
        /// </summary>
        public static string APPS_ATTACH_FILE_TYPE_SUPPORTED {
            get {
                return ResourceManager.GetString("APPS_ATTACH_FILE_TYPE_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารแนบเพิ่มเติม.
        /// </summary>
        public static string APPS_ATTACH_FILES {
            get {
                return ResourceManager.GetString("APPS_ATTACH_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ: หลักฐานข้างต้น จะต้องลงนามรับรองสำเนาถูกต้อง.
        /// </summary>
        public static string APPS_ATTACH_REMARK {
            get {
                return ResourceManager.GetString("APPS_ATTACH_REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอใช้ไฟฟ้า (นครหลวง).
        /// </summary>
        public static string APPS_CHOOSE_MEA {
            get {
                return ResourceManager.GetString("APPS_CHOOSE_MEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอใช้น้ำประปา (นครหลวง).
        /// </summary>
        public static string APPS_CHOOSE_MWA {
            get {
                return ResourceManager.GetString("APPS_CHOOSE_MWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอใช้ไฟฟ้า (ส่วนภูมิภาค).
        /// </summary>
        public static string APPS_CHOOSE_PEA {
            get {
                return ResourceManager.GetString("APPS_CHOOSE_PEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอใช้น้ำประปา (ส่วนภูมิภาค).
        /// </summary>
        public static string APPS_CHOOSE_PWA {
            get {
                return ResourceManager.GetString("APPS_CHOOSE_PWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดเลือกการขอใช้สาธารณูปโภค.
        /// </summary>
        public static string APPS_CHOOSE_REQUEST {
            get {
                return ResourceManager.GetString("APPS_CHOOSE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอใช้โทรศัพท์ (TOT).
        /// </summary>
        public static string APPS_CHOOSE_TOT {
            get {
                return ResourceManager.GetString("APPS_CHOOSE_TOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบฟอร์มขอใช้สาธารณูปโภค.
        /// </summary>
        public static string APPS_FORM_UTILITY {
            get {
                return ResourceManager.GetString("APPS_FORM_UTILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาติดต่อ contact@ega.or.th สำหรับข้อมูลเพิ่มเติม.
        /// </summary>
        public static string APPS_GETBRANCH_INFO {
            get {
                return ResourceManager.GetString("APPS_GETBRANCH_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อฐานข้อมูลสาขาของการไฟฟ้าได้.
        /// </summary>
        public static string APPS_GETBRANCH_MEA {
            get {
                return ResourceManager.GetString("APPS_GETBRANCH_MEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อฐานข้อมูลสาขาของการประปาได้.
        /// </summary>
        public static string APPS_GETBRANCH_MWA {
            get {
                return ResourceManager.GetString("APPS_GETBRANCH_MWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาด.
        /// </summary>
        public static string APPS_GETBRANCH_TIMEOUT {
            get {
                return ResourceManager.GetString("APPS_GETBRANCH_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทธุรกิจ.
        /// </summary>
        public static string APPS_MEA_BIZ_TYPE {
            get {
                return ResourceManager.GetString("APPS_MEA_BIZ_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟฟ้าเขตที่รับผิดชอบ.
        /// </summary>
        public static string APPS_MEA_BRANCH {
            get {
                return ResourceManager.GetString("APPS_MEA_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดคำขอใช้ไฟฟ้า (นครหลวง).
        /// </summary>
        public static string APPS_MEA_DETAIL {
            get {
                return ResourceManager.GetString("APPS_MEA_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กิจการประเภทอื่นนอกเหนือจากบ้านอยู่อาศัย.
        /// </summary>
        public static string APPS_MEA_LOCATION_BIZ {
            get {
                return ResourceManager.GetString("APPS_MEA_LOCATION_BIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บ้านอยู่อาศัย.
        /// </summary>
        public static string APPS_MEA_LOCATION_HOUSE {
            get {
                return ResourceManager.GetString("APPS_MEA_LOCATION_HOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทสถานที่ขอใช้ไฟฟ้า.
        /// </summary>
        public static string APPS_MEA_LOCATION_TYPE {
            get {
                return ResourceManager.GetString("APPS_MEA_LOCATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดเครื่องวัด.
        /// </summary>
        public static string APPS_MEA_MEASUREMENT {
            get {
                return ResourceManager.GetString("APPS_MEA_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟใหม่.
        /// </summary>
        public static string APPS_MEA_NEW_APPLICATION {
            get {
                return ResourceManager.GetString("APPS_MEA_NEW_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทการบริการ.
        /// </summary>
        public static string APPS_MEA_SERVICE_TYPE {
            get {
                return ResourceManager.GetString("APPS_MEA_SERVICE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลังสินค้า.
        /// </summary>
        public static string APPS_MEA_WAREHOUSE {
            get {
                return ResourceManager.GetString("APPS_MEA_WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขาที่ผู้ใช้น้ำต้องการติดตั้ง.
        /// </summary>
        public static string APPS_MWA_BRANCH {
            get {
                return ResourceManager.GetString("APPS_MWA_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขคำร้องของการประปานครหลวง (อ้างอิง).
        /// </summary>
        public static string APPS_MWA_CIS_CODE {
            get {
                return ResourceManager.GetString("APPS_MWA_CIS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดคำขอใช้น้ำประปา (นครหลวง).
        /// </summary>
        public static string APPS_MWA_DETAIL {
            get {
                return ResourceManager.GetString("APPS_MWA_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดคำขอใช้ไฟฟ้า (ส่วนภูมิภาค).
        /// </summary>
        public static string APPS_PEA_DETAIL {
            get {
                return ResourceManager.GetString("APPS_PEA_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดคำขอใช้น้ำประปา (ส่วนภูมิภาค).
        /// </summary>
        public static string APPS_PWA_DETAIL {
            get {
                return ResourceManager.GetString("APPS_PWA_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการบันทึกข้อมูล.
        /// </summary>
        public static string APPS_SUBMIT_CONFIRMATION {
            get {
                return ResourceManager.GetString("APPS_SUBMIT_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อกำหนดและนโยบายการให้บริการ biz.govchannel.go.th และ service.govchannel.go.th.
        /// </summary>
        public static string APPS_TERM_OF_USE {
            get {
                return ResourceManager.GetString("APPS_TERM_OF_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;
        ///        &lt;b&gt;คำนิยาม&lt;/b&gt;&lt;br /&gt;
        ///        “ผู้ให้บริการ” หมายความถึง หน่วยงานของรัฐ, รัฐวิสาหกิจ หรือหน่วยงานใดๆ ที่มีบริการบนระบบบริการนี้&lt;br /&gt;
        ///        “ผู้ใช้บริการ” หมายความถึง บุคคลธรรมดาหรือนิติบุคคลที่ใช้บริการใดๆ ของผู้ให้บริการ&lt;br /&gt;
        ///        “บริการ” หมายความรวมถึง การใช้เว็บไซต์ของ biz.govchannel.go.th และ service.govchannel.go.th&lt;br /&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APPS_TERMS_AND_CONDITIONS {
            get {
                return ResourceManager.GetString("APPS_TERMS_AND_CONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดคำขอใช้โทรศัพท์ (TOT).
        /// </summary>
        public static string APPS_TOT_DETAIL {
            get {
                return ResourceManager.GetString("APPS_TOT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทการบริการ.
        /// </summary>
        public static string APPS_TOT_SERVICE_TYPE {
            get {
                return ResourceManager.GetString("APPS_TOT_SERVICE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลหรือแนบไฟล์ให้ครบถ้วนและถูกต้อง.
        /// </summary>
        public static string APPS_VALIDATE_FALSE_TEXT {
            get {
                return ResourceManager.GetString("APPS_VALIDATE_FALSE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลให้ครบถ้วนและถูกต้อง.
        /// </summary>
        public static string APPS_VALIDATE_FALSE_TEXT_CITIZEN {
            get {
                return ResourceManager.GetString("APPS_VALIDATE_FALSE_TEXT_CITIZEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถส่งข้อมูลได้.
        /// </summary>
        public static string APPS_VALIDATE_FALSE_TITLE {
            get {
                return ResourceManager.GetString("APPS_VALIDATE_FALSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดผู้ขอใช้งาน.
        /// </summary>
        public static string BIZ_APPLICANT_INFOMATION {
            get {
                return ResourceManager.GetString("BIZ_APPLICANT_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่สาขา.
        /// </summary>
        public static string BIZ_BRANCH {
            get {
                return ResourceManager.GetString("BIZ_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตัวอย่างเช่น 00000.
        /// </summary>
        public static string BIZ_BRANCH_PLACEHOLDER {
            get {
                return ResourceManager.GetString("BIZ_BRANCH_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรณีผู้ดำเนินการเป็นชาวต่างชาติที่ไม่มีสัญชาติไทย ให้ระบุเลขที่หนังสือเดินทางและแนบเอกสารสำเนาหนังสือเดินทาง.
        /// </summary>
        public static string BIZ_COMMITTEE_NOTE {
            get {
                return ResourceManager.GetString("BIZ_COMMITTEE_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดำเนินการโดย.
        /// </summary>
        public static string BIZ_COMMITTEES {
            get {
                return ResourceManager.GetString("BIZ_COMMITTEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอใช้ในนาม.
        /// </summary>
        public static string BIZ_NAME {
            get {
                return ResourceManager.GetString("BIZ_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขทะเบียนการค้า.
        /// </summary>
        public static string BIZ_REG_ID {
            get {
                return ResourceManager.GetString("BIZ_REG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขประจำตัวผู้เสียภาษี 13 หลัก.
        /// </summary>
        public static string BIZ_TAX_ID {
            get {
                return ResourceManager.GetString("BIZ_TAX_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขโทรศัพท์.
        /// </summary>
        public static string BIZ_TEL {
            get {
                return ResourceManager.GetString("BIZ_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทบริษัท.
        /// </summary>
        public static string BIZ_TYPE {
            get {
                return ResourceManager.GetString("BIZ_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอมรับ.
        /// </summary>
        public static string BTN_ACCEPT {
            get {
                return ResourceManager.GetString("BTN_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        public static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ยอมรับ.
        /// </summary>
        public static string BTN_DECLINE {
            get {
                return ResourceManager.GetString("BTN_DECLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้ Google Maps ช่วยเลือกสาขา.
        /// </summary>
        public static string BTN_GMAPS {
            get {
                return ResourceManager.GetString("BTN_GMAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตกลง.
        /// </summary>
        public static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหนังสือรับรองการจดทะเบียนนิติบุคคล .
        /// </summary>
        public static string CERTIFICATION_OF_COMPANY_REGISTRATION_COPY {
            get {
                return ResourceManager.GetString("CERTIFICATION_OF_COMPANY_REGISTRATION_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหนังสือรับรองการจดทะเบียนนิติบุคคล (มีอายุไม่เกิน 6 เดือนนับถึงวันที่ยื่นคำขอ).
        /// </summary>
        public static string CERTIFICATION_OF_COMPANY_REGISTRATION_COPY_6M {
            get {
                return ResourceManager.GetString("CERTIFICATION_OF_COMPANY_REGISTRATION_COPY_6M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบทะเบียนภาษีธุรกิจเฉพาะ.
        /// </summary>
        public static string CERTIFICATION_OF_SPECIFIED_BUSINESS {
            get {
                return ResourceManager.GetString("CERTIFICATION_OF_SPECIFIED_BUSINESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน เดือน ปี(พ.ศ.) ที่เกิด.
        /// </summary>
        public static string CITIZEN_BIRTH_DATE {
            get {
                return ResourceManager.GetString("CITIZEN_BIRTH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน 13 หลัก.
        /// </summary>
        public static string CITIZEN_ID {
            get {
                return ResourceManager.GetString("CITIZEN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string CITIZEN_LASTNAME {
            get {
                return ResourceManager.GetString("CITIZEN_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string CITIZEN_NAME {
            get {
                return ResourceManager.GetString("CITIZEN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้า.
        /// </summary>
        public static string CITIZEN_PREFIX {
            get {
                return ResourceManager.GetString("CITIZEN_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบทะเบียนพาณิชย์.
        /// </summary>
        public static string COMMERCIAL_REGISTRATION {
            get {
                return ResourceManager.GetString("COMMERCIAL_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสถานประกอบการ (ชื่อนิติบุคคล) ภาษาอังกฤษ.
        /// </summary>
        public static string COMPANY_NAME_EN {
            get {
                return ResourceManager.GetString("COMPANY_NAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสถานประกอบการ (ชื่อนิติบุคคล) ภาษาไทย.
        /// </summary>
        public static string COMPANY_NAME_TH {
            get {
                return ResourceManager.GetString("COMPANY_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลสำหรับติดต่อ.
        /// </summary>
        public static string CONTACT_EMAIL {
            get {
                return ResourceManager.GetString("CONTACT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อของผู้ติดต่อ.
        /// </summary>
        public static string CONTACT_FIRSTNAME {
            get {
                return ResourceManager.GetString("CONTACT_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประจำตัวประชาชน 13 หลัก ของผู้ติดต่อ.
        /// </summary>
        public static string CONTACT_ID {
            get {
                return ResourceManager.GetString("CONTACT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดของผู้ติดต่อ.
        /// </summary>
        public static string CONTACT_INFORMATION {
            get {
                return ResourceManager.GetString("CONTACT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุลของผู้ติดต่อ.
        /// </summary>
        public static string CONTACT_LASTNAME {
            get {
                return ResourceManager.GetString("CONTACT_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์สำหรับติดต่อ.
        /// </summary>
        public static string CONTACT_TEL {
            get {
                return ResourceManager.GetString("CONTACT_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญญาจะซื้อ จะขาย.
        /// </summary>
        public static string CONTRACT_AGREEMENT {
            get {
                return ResourceManager.GetString("CONTRACT_AGREEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลับไปยังก่อนหน้า.
        /// </summary>
        public static string DBD_ERROR_BACK {
            get {
                return ResourceManager.GetString("DBD_ERROR_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลองใหม่อีกครั้ง.
        /// </summary>
        public static string DBD_ERROR_RELOAD {
            get {
                return ResourceManager.GetString("DBD_ERROR_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาลองใหม่อีกครั้ง หรือกลับไปยังก่อนหน้า.
        /// </summary>
        public static string DBD_ERROR_TEXT {
            get {
                return ResourceManager.GetString("DBD_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อข้อมูลระหว่างหน่วยงานได้ในขณะนี้.
        /// </summary>
        public static string DBD_ERROR_TITLE {
            get {
                return ResourceManager.GetString("DBD_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอก.
        /// </summary>
        public static string FIELD_REQUIRED_1 {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงในช่องว่าง.
        /// </summary>
        public static string FIELD_REQUIRED_2 {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากำหนดรหัสประจำบ้านตามทะเบียนบ้านโดยตัวเลข 0-9 จำนวน 11 หลัก.
        /// </summary>
        public static string FIELD_REQUIRED_ADDRESS_ID {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_ADDRESS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาแนบเอกสารข้างต้น.
        /// </summary>
        public static string FIELD_REQUIRED_ATTACHFILES {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_ATTACHFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากำหนดสาขาโดยตัวเลข 0-9 จำนวน 5 หลัก.
        /// </summary>
        public static string FIELD_REQUIRED_BIZ_BRANCH {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_BIZ_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากำหนดเลขบัตรประจำตัวประชาชนโดยตัวเลข 0-9 จำนวน 13 หลัก.
        /// </summary>
        public static string FIELD_REQUIRED_CITIZEN_ID {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_CITIZEN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกสถานที่ขอติดตั้งในแผนที่.
        /// </summary>
        public static string FIELD_REQUIRED_LATLNG {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_LATLNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือก.
        /// </summary>
        public static string FIELD_REQUIRED_SELECTFORM {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_SELECTFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากำหนดเลขประจำตัวผู้เสียภาษีโดยตัวเลข 0-9 จำนวน 13 หลัก.
        /// </summary>
        public static string FIELD_REQUIRED_TAX_ID {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_TAX_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากำหนดรหัสไปรษณีย์โดยตัวเลข 0-9 จำนวน 5 หลัก.
        /// </summary>
        public static string FIELD_REQUIRED_ZIP_CODE {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED_ZIP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบสําคัญประจำตัวคนต่างด้าว.
        /// </summary>
        public static string FOREIGNER_IDENTITY_COPY {
            get {
                return ResourceManager.GetString("FOREIGNER_IDENTITY_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหนังสือเดินทาง.
        /// </summary>
        public static string FOREIGNER_PASSPORT_COPY {
            get {
                return ResourceManager.GetString("FOREIGNER_PASSPORT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทนิติบุคคล.
        /// </summary>
        public static string GENERAL_INFORMATION_JURISTIC_TYPE {
            get {
                return ResourceManager.GetString("GENERAL_INFORMATION_JURISTIC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนังสือให้หมายเลขบ้านที่ขอใช้บริการ.
        /// </summary>
        public static string HOUSE_ID_DOC_COPY {
            get {
                return ResourceManager.GetString("HOUSE_ID_DOC_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาทะเบียนบ้านที่ขอใช้บริการ ซึ่งระบุชื่อผู้ขอใช้บริการเป็นเจ้าของบ้าน หรือหนังสือให้หมายเลขบ้าน หรือสัญญาซื้อขายที่ดินพร้อมสิ่งปลูกสร้าง.
        /// </summary>
        public static string HOUSE_OWNER_DOCUMENT_COPY {
            get {
                return ResourceManager.GetString("HOUSE_OWNER_DOCUMENT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาทะเบียนบ้านที่ขอใช้บริการ ซึ่งระบุชื่อผู้ขอใช้บริการเป็นเจ้าของบ้าน.
        /// </summary>
        public static string HOUSE_OWNER_REG_COPY {
            get {
                return ResourceManager.GetString("HOUSE_OWNER_REG_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาทะเบียนบ้านที่ขอใช้บริการ.
        /// </summary>
        public static string HOUSEHOLD_REGISTRATION_COPY {
            get {
                return ResourceManager.GetString("HOUSEHOLD_REGISTRATION_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ่ายบัตรประจําตัวประชาชน (คนต่างด้าวใช้สําเนาหนังสือเดินทางหรือใบสําคัญประจำตัวคนต่างด้าว).
        /// </summary>
        public static string IDENTITY_COPY {
            get {
                return ResourceManager.GetString("IDENTITY_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักฐานการจ่ายภาษีบุคคลธรรมดา (ภ.ง.ด. ๙๐).
        /// </summary>
        public static string INDIVIDUAL_TAXPAYER_COPY {
            get {
                return ResourceManager.GetString("INDIVIDUAL_TAXPAYER_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เขียนที่.
        /// </summary>
        public static string INFORMATION_HEADER_REQUEST_AT {
            get {
                return ResourceManager.GetString("INFORMATION_HEADER_REQUEST_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน/เดือน/ปีที่ยื่นคำขอ.
        /// </summary>
        public static string INFORMATION_HEADER_REQUEST_DATE {
            get {
                return ResourceManager.GetString("INFORMATION_HEADER_REQUEST_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขออนุญาตในฐานะบุคคลธรรมดาหรือนิติบุคคล.
        /// </summary>
        public static string INFORMATION_REQUEST_AS {
            get {
                return ResourceManager.GetString("INFORMATION_REQUEST_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อำเภอ.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_AMPHUR {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_AMPHUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาคาร.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_BUILDING {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต่อ.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_EXT {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรสาร.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_FAX {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชั้น.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_FLOOR {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมู่.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_MOO {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_MOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_NO {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปษณีย์.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_POSTCODE {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จังหวัด.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_PROVINCE {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถนน.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_ROAD {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_ROAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหาที่อยู่.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_SEARCH {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ซอย.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_SOI {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_SOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_TELEPHONE {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำบล.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_TUMBOL {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_TUMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมู่บ้าน.
        /// </summary>
        public static string INFORMATION_STORE_ADDRESS_VILLAGE {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_ADDRESS_VILLAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พื้นที่ใช้สอย (ตารางเมตร).
        /// </summary>
        public static string INFORMATION_STORE_AREA {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทของผู้ให้เช่า/ให้ใช้สถานที่.
        /// </summary>
        public static string INFORMATION_STORE_BUILDING_RENTING_TYPE_HEADER {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_BUILDING_RENTING_TYPE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาคารที่ตั้งร้านของคุณมีลักษณะกรรมสิทธิ์เป็นแบบ.
        /// </summary>
        public static string INFORMATION_STORE_BUILDING_TYPE_HEADER {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_BUILDING_TYPE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ร้านของคุณตั้งอยู่ในพื้นที่ภาครัฐ/ราชพัสดุหรือไม่.
        /// </summary>
        public static string INFORMATION_STORE_IN_GOVERNMENT_AREA_OPTION {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_IN_GOVERNMENT_AREA_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อร้าน (ภาษาอังกฤษ).
        /// </summary>
        public static string INFORMATION_STORE_NAME_EN {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_NAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อร้าน (ภาษาไทย).
        /// </summary>
        public static string INFORMATION_STORE_NAME_TH {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้ที่อยู่เดียวกันกับนิติบุคคล.
        /// </summary>
        public static string INFORMATION_STORE_USE_JURISTIC_ADDRESS_TRUE {
            get {
                return ResourceManager.GetString("INFORMATION_STORE_USE_JURISTIC_ADDRESS_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญญาซื้อขายที่ดินพร้อมสิ่งปลูกสร้าง.
        /// </summary>
        public static string LANDWITHBUILDING_CONTRACT_AGREEMENT {
            get {
                return ResourceManager.GetString("LANDWITHBUILDING_CONTRACT_AGREEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญญาเช่าซื้อที่ดินพร้อมอาคารหรือที่มีสิ่งก่อสร้างถาวรตั้งอยู่.
        /// </summary>
        public static string LANDWITHBUILDING_RENTAL_AGREEMENT {
            get {
                return ResourceManager.GetString("LANDWITHBUILDING_RENTAL_AGREEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาลากหมุดเพื่อกำหนดพิกัดของสถานที่ขอติดตั้ง.
        /// </summary>
        public static string MAP_MODAL_HOWTO {
            get {
                return ResourceManager.GetString("MAP_MODAL_HOWTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกสาขาของการไฟฟ้าโดยการปักหมุดบนแผนที่.
        /// </summary>
        public static string MEA_BRANCH_REQUIRED {
            get {
                return ResourceManager.GetString("MEA_BRANCH_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักฐานการเป็นผู้ประกอบการ เช่น ใบทะเบียนภาษีมูลค่าเพิ่ม ใบทะเบียนภาษีธุรกิจเฉพาะ ใบทะเบียนพาณิชย์ หลักฐานการจ่ายภาษีบุคคลธรรมดา(ภ.ง.ด. ๙๐) ฯลฯ.
        /// </summary>
        public static string MEA_CERTIFICATION_OF_OPERATOR_COPY {
            get {
                return ResourceManager.GetString("MEA_CERTIFICATION_OF_OPERATOR_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาทะเบียนบ้านที่มีชื่อของผู้ใช้ไฟฟ้า.
        /// </summary>
        public static string MEA_HOUSEHOLD_REGISTRATION_OF_APPLICANT_COPY {
            get {
                return ResourceManager.GetString("MEA_HOUSEHOLD_REGISTRATION_OF_APPLICANT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ประกอบการในสถานที่ใช้ไฟฟ้า.
        /// </summary>
        public static string MEA_OPTION_OPERATOR {
            get {
                return ResourceManager.GetString("MEA_OPTION_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เจ้าของที่ดินหรือเจ้าของสถานที่ใช้ไฟฟ้า.
        /// </summary>
        public static string MEA_OPTION_OWNER {
            get {
                return ResourceManager.GetString("MEA_OPTION_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้เช่าหรือผู้เช่าซื้อสถานที่ใช้ไฟฟ้า.
        /// </summary>
        public static string MEA_OPTION_RENT {
            get {
                return ResourceManager.GetString("MEA_OPTION_RENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ขอใช้ไฟฟ้ามีชื่ออยู่ในทะเบียนบ้านที่ใช้ไฟฟ้า.
        /// </summary>
        public static string MEA_OPTION_RESIDENT {
            get {
                return ResourceManager.GetString("MEA_OPTION_RESIDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  กรุณาเลือกขนาดเครื่องวัดที่ต้องการติดตั้ง.
        /// </summary>
        public static string MEA_OSS_TYPE_REQUIRED {
            get {
                return ResourceManager.GetString("MEA_OSS_TYPE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกสาขาของการประปาโดยการปักหมุดบนแผนที่.
        /// </summary>
        public static string MWA_BRANCH_REQUIRED {
            get {
                return ResourceManager.GetString("MWA_BRANCH_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เจ้าของสถานที่.
        /// </summary>
        public static string MWA_OPTION_OWNER {
            get {
                return ResourceManager.GetString("MWA_OPTION_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เช่าสถานที่.
        /// </summary>
        public static string MWA_OPTION_RENT {
            get {
                return ResourceManager.GetString("MWA_OPTION_RENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดมิเตอร์.
        /// </summary>
        public static string PEA_METER_SIZE {
            get {
                return ResourceManager.GetString("PEA_METER_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทมิเตอร์.
        /// </summary>
        public static string PEA_METER_TYPE {
            get {
                return ResourceManager.GetString("PEA_METER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทกิจการ.
        /// </summary>
        public static string PEA_TSIC {
            get {
                return ResourceManager.GetString("PEA_TSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นาย.
        /// </summary>
        public static string PREFIX_MR {
            get {
                return ResourceManager.GetString("PREFIX_MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นาง.
        /// </summary>
        public static string PREFIX_MRS {
            get {
                return ResourceManager.GetString("PREFIX_MRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to น.ส..
        /// </summary>
        public static string PREFIX_MS {
            get {
                return ResourceManager.GetString("PREFIX_MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน/เดือน/ปี ที่จดทะเบียนนิติบุคคล.
        /// </summary>
        public static string REGISTER_DATE {
            get {
                return ResourceManager.GetString("REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญญาเช่าหรือสัญญาเช่าซื้อที่ดินพร้อมอาคารหรือที่มีสิ่งก่อสร้างถาวรตั้งอยู่.
        /// </summary>
        public static string RENTAL_AGREEMENT_COPY {
            get {
                return ResourceManager.GetString("RENTAL_AGREEMENT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญญาเช่า.
        /// </summary>
        public static string RENTAL_AGREEMENT_DOCUMENT {
            get {
                return ResourceManager.GetString("RENTAL_AGREEMENT_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การขออนุญาตครั้งนี้.
        /// </summary>
        public static string REQUESTOR_INFORMATION_REQUEST_TYPE_OPTION {
            get {
                return ResourceManager.GetString("REQUESTOR_INFORMATION_REQUEST_TYPE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายชื่อผู้ขออนุญาต.
        /// </summary>
        public static string REQUESTOR_INFORMATION_REQUESTOR_HEADER {
            get {
                return ResourceManager.GetString("REQUESTOR_INFORMATION_REQUESTOR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อายุ.
        /// </summary>
        public static string SELL_FOOD_FOOD_MANAGER_INFO_AGE {
            get {
                return ResourceManager.GetString("SELL_FOOD_FOOD_MANAGER_INFO_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string SELL_FOOD_FOOD_MANAGER_INFO_FIRSTNAME {
            get {
                return ResourceManager.GetString("SELL_FOOD_FOOD_MANAGER_INFO_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string SELL_FOOD_FOOD_MANAGER_INFO_LASTNAME {
            get {
                return ResourceManager.GetString("SELL_FOOD_FOOD_MANAGER_INFO_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้า.
        /// </summary>
        public static string SELL_FOOD_FOOD_MANAGER_INFO_TITLE {
            get {
                return ResourceManager.GetString("SELL_FOOD_FOOD_MANAGER_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายชื่อผู้ที่ต้องสัมผัสอาหาร เช่น พ่อครัว/แม่ครัว พนักงานเสิร์ฟ ฯลฯ.
        /// </summary>
        public static string SELL_FOOD_FOOD_WORKER_INFO {
            get {
                return ResourceManager.GetString("SELL_FOOD_FOOD_WORKER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทการขออนุญาต.
        /// </summary>
        public static string SELL_FOOD_INFORMATION_APP_TYPE {
            get {
                return ResourceManager.GetString("SELL_FOOD_INFORMATION_APP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทสถานประกอบการ.
        /// </summary>
        public static string SELL_FOOD_INFORMATION_BUSINESS_TYPE {
            get {
                return ResourceManager.GetString("SELL_FOOD_INFORMATION_BUSINESS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทอาหาร.
        /// </summary>
        public static string SELL_FOOD_INFORMATION_FOOD_TYPE {
            get {
                return ResourceManager.GetString("SELL_FOOD_INFORMATION_FOOD_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบอนุญาต หรือหนังสือฯ ที่ยื่นขอ.
        /// </summary>
        public static string SELL_FOOD_INFORMATION_LICENSE_TYPE {
            get {
                return ResourceManager.GetString("SELL_FOOD_INFORMATION_LICENSE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญชาติ.
        /// </summary>
        public static string SELL_FOOD_INFORMATION_NATIONALITY_OPTION {
            get {
                return ResourceManager.GetString("SELL_FOOD_INFORMATION_NATIONALITY_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพื่อประกอบกิจการ.
        /// </summary>
        public static string SELL_FOOD_INFORMATION_PURPOSE_OPTION {
            get {
                return ResourceManager.GetString("SELL_FOOD_INFORMATION_PURPOSE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลิกเพื่อยอมรับ.
        /// </summary>
        public static string STRING_BEFOR_SUBMIT_1 {
            get {
                return ResourceManager.GetString("STRING_BEFOR_SUBMIT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขการให้บริการ.
        /// </summary>
        public static string STRING_BEFOR_SUBMIT_2 {
            get {
                return ResourceManager.GetString("STRING_BEFOR_SUBMIT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การดำเนินการทุกครั้ง.
        /// </summary>
        public static string STRING_BEFOR_SUBMIT_3 {
            get {
                return ResourceManager.GetString("STRING_BEFOR_SUBMIT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ่ายบัตรประจําตัวประชาชน.
        /// </summary>
        public static string THAI_IDENTITY_COPY {
            get {
                return ResourceManager.GetString("THAI_IDENTITY_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทเอกสารที่ต้องการอัปโหลด.
        /// </summary>
        public static string TYPE_OF_DOCUMENT {
            get {
                return ResourceManager.GetString("TYPE_OF_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบทะเบียนภาษีมูลค่าเพิ่ม (ภ.พ. 20).
        /// </summary>
        public static string VAT_REGISTRATION {
            get {
                return ResourceManager.GetString("VAT_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบทะเบียนภาษีมูลค่าเพิ่ม (ภ.พ. 20) (ถ้ามี).
        /// </summary>
        public static string VAT_REGISTRATION_OPTIONAL {
            get {
                return ResourceManager.GetString("VAT_REGISTRATION_OPTIONAL", resourceCulture);
            }
        }
    }
}
