//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactUs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactUs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.ContactUs", typeof(ContactUs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรประชาชน.
        /// </summary>
        public static string CITIZEN_ID {
            get {
                return ResourceManager.GetString("CITIZEN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิดทำการ.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ศูนย์บริการประชาชน 
        ///(จุดบริการประชาชน 1111) 
        ///สำนักงานปลัดสำนักนายกรัฐมนตรีทำเนียบรัฐบาล ถนนพิษณุโลก เขตดุสิต กทม. (ประตู 4).
        /// </summary>
        public static string CONTACT_ADDRESS {
            get {
                return ResourceManager.GetString("CONTACT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to administrator@opdc.go.th.
        /// </summary>
        public static string CONTACT_EMAIL {
            get {
                return ResourceManager.GetString("CONTACT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตู้ ปณ.1111 ทำเนียบรัฐบาล กรุงเทพมหานคร 10302 (ไม่ต้องติดแสตมป์).
        /// </summary>
        public static string CONTACT_MAIL {
            get {
                return ResourceManager.GetString("CONTACT_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สายด่วน 1111 กด 22 (24 ชั่วโมง).
        /// </summary>
        public static string CONTACT_NO {
            get {
                return ResourceManager.GetString("CONTACT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ติดต่อเรา.
        /// </summary>
        public static string CONTACT_US {
            get {
                return ResourceManager.GetString("CONTACT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.1111.go.th.
        /// </summary>
        public static string CONTACT_WEB {
            get {
                return ResourceManager.GetString("CONTACT_WEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณ {{FULL_NAME}} ได้ติดต่อเรื่อง {{TYPE}} โดยมีรายละเอียดดังนี้ &lt;p&gt;&lt;/p&gt; {{DETAIL}} &lt;p&gt;&lt;/p&gt; &lt;b&gt;ข้อมูลผู้ติดต่อ&lt;/b&gt; &lt;br/&gt; &lt;b&gt;เลขบัตรประชาชน&lt;/b&gt; {{CITIZENID}}&lt;b&gt;อีเมล&lt;/b&gt; {{EMAIL}}&lt;br/&gt;&lt;b&gt;เบอร์โทรศัพท์&lt;/b&gt; {{MOBILENO}}&lt;br/&gt;.
        /// </summary>
        public static string EMAIL_BODY {
            get {
                return ResourceManager.GetString("EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลไม่ถูกต้อง.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BizPortal] ติดต่อเรื่อง {0}.
        /// </summary>
        public static string EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันหยุดราชการที่ปิดทำการ.
        /// </summary>
        public static string GOVERNMENT_CLOSE {
            get {
                return ResourceManager.GetString("GOVERNMENT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการให้ติดต่อกลับ.
        /// </summary>
        public static string IS_CONTACT_BACK {
            get {
                return ResourceManager.GetString("IS_CONTACT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ นามสกุล.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาเปิด - ปิดทำการวันนี้.
        /// </summary>
        public static string OFFICE_HOUR {
            get {
                return ResourceManager.GetString("OFFICE_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิดทำการ.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จันทร์ - ศุกร์ 8:30 - 16:30.
        /// </summary>
        public static string OPEN_TIME {
            get {
                return ResourceManager.GetString("OPEN_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ศูนย์บริการประชาชน 
        ///สำนักงานปลัดนายกรัฐมนตรี.
        /// </summary>
        public static string OWNER_NAME {
            get {
                return ResourceManager.GetString("OWNER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์เลขบัตรประชาชน....
        /// </summary>
        public static string PLACE_CITIZEN_ID {
            get {
                return ResourceManager.GetString("PLACE_CITIZEN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์รายละเอียด.
        /// </summary>
        public static string PLACE_DETAIL {
            get {
                return ResourceManager.GetString("PLACE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์อีเมล....
        /// </summary>
        public static string PLACE_EMAIL {
            get {
                return ResourceManager.GetString("PLACE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์ชื่อ - นามสกุล....
        /// </summary>
        public static string PLACE_NAME {
            get {
                return ResourceManager.GetString("PLACE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์เบอร์โทรศัพท์....
        /// </summary>
        public static string PLACE_PHONE_NO {
            get {
                return ResourceManager.GetString("PLACE_PHONE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุเลขบัตรประชาชน.
        /// </summary>
        public static string PLEASE_ENTER_CITIZENID {
            get {
                return ResourceManager.GetString("PLEASE_ENTER_CITIZENID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุอีเมล.
        /// </summary>
        public static string PLEASE_ENTER_EMAIL {
            get {
                return ResourceManager.GetString("PLEASE_ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุข้อความ.
        /// </summary>
        public static string PLEASE_ENTER_MESSAGE {
            get {
                return ResourceManager.GetString("PLEASE_ENTER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หากต้องการให้เราติดต่อกลับ กรุณากรอกข้อมูลเพิ่มเติม.
        /// </summary>
        public static string PLEASE_ENTER_MORE_DETAIL {
            get {
                return ResourceManager.GetString("PLEASE_ENTER_MORE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุชื่อ นามสกุล.
        /// </summary>
        public static string PLEASE_ENTER_NAME {
            get {
                return ResourceManager.GetString("PLEASE_ENTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุเบอร์โทรศัพท์.
        /// </summary>
        public static string PLEASE_ENTER_TELEPHONE {
            get {
                return ResourceManager.GetString("PLEASE_ENTER_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกคำถาม.
        /// </summary>
        public static string PLEASE_SELECT_QUESTION {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ร้องเรียนงานบริการภาครัฐ.
        /// </summary>
        public static string QUESTION_CLAIM {
            get {
                return ResourceManager.GetString("QUESTION_CLAIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สอบถามข้อมูลเพิ่มเติมเกี่ยวกับการติดต่อราชการ.
        /// </summary>
        public static string QUESTION_CONTACT {
            get {
                return ResourceManager.GetString("QUESTION_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่นๆ.
        /// </summary>
        public static string QUESTION_OTHER {
            get {
                return ResourceManager.GetString("QUESTION_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แจ้งปัญหาการใช้งานเว็บไซต์.
        /// </summary>
        public static string QUESTION_WEBSITE {
            get {
                return ResourceManager.GetString("QUESTION_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่ง.
        /// </summary>
        public static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งอีเมลสำเร็จ.
        /// </summary>
        public static string SEND_MAIL_COMPLETED {
            get {
                return ResourceManager.GetString("SEND_MAIL_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งอีเมลไม่สำเร็จ กรุณาลองอีกครั้ง.
        /// </summary>
        public static string SEND_MAIL_FAILED {
            get {
                return ResourceManager.GetString("SEND_MAIL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรื่อง....
        /// </summary>
        public static string SUBJECT {
            get {
                return ResourceManager.GetString("SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์.
        /// </summary>
        public static string TELEPHONE {
            get {
                return ResourceManager.GetString("TELEPHONE", resourceCulture);
            }
        }
    }
}
