//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.FileType", typeof(FileType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ่ายหนังสือรับรองการจดทะเบียนนิติบุคคลพร้อมวัตถุประสงค์.
        /// </summary>
        public static string CERTIFICATION_OF_COMPANY_REGISTRATION_COPY {
            get {
                return ResourceManager.GetString("CERTIFICATION_OF_COMPANY_REGISTRATION_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักฐานการเป็นผู้ประกอบการ เช่น ใบทะเบียนภาษีมูลค่าเพิ่ม ใบทะเบียนภาษีธุรกิจเฉพาะ ใบทะเบียนพาณิชย์ หลักฐานการจ่ายภาษีบุคคลธรรมดา(ภ.ง.ด. ๙๐) ฯลฯ.
        /// </summary>
        public static string CERTIFICATION_OF_OPERATOR_COPY {
            get {
                return ResourceManager.GetString("CERTIFICATION_OF_OPERATOR_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หลักฐานการแสดงตัวของนายจ้าง.
        /// </summary>
        public static string EMPLOYER_IDENTITY_COPY {
            get {
                return ResourceManager.GetString("EMPLOYER_IDENTITY_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบขึ้นทะเบียนนายจ้าง (สปส.1-01).
        /// </summary>
        public static string EMPLOYER_REGISTER_FORM_1_0_1 {
            get {
                return ResourceManager.GetString("EMPLOYER_REGISTER_FORM_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชาวต่างชาติ.
        /// </summary>
        public static string FOREIGNER {
            get {
                return ResourceManager.GetString("FOREIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาทะเบียนที่ขอใช้บริการ ซึ่งระบุชื่อผู้ขอใช้บริการเป็นเจ้าของบ้าน หรือหนังสือให้หมายเลขบ้าน หรือสัญญาซื้อขายบ้านพร้อมที่ดิน หรือสัญญาจะซื้อจะขาย.
        /// </summary>
        public static string HOUSE_OWNER_DOCUMENT_COPY {
            get {
                return ResourceManager.GetString("HOUSE_OWNER_DOCUMENT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ่ายทะเบียนบ้าน.
        /// </summary>
        public static string HOUSEHOLD_REGISTRATION_COPY {
            get {
                return ResourceManager.GetString("HOUSEHOLD_REGISTRATION_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาทะเบียนบ้านที่มีชื่อของผู้ใช้ไฟฟ้า.
        /// </summary>
        public static string HOUSEHOLD_REGISTRATION_OF_APPLICANT_COPY {
            get {
                return ResourceManager.GetString("HOUSEHOLD_REGISTRATION_OF_APPLICANT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สําเนาหรือภาพถ่ายบัตรประจําตัวประชาชน (คนต่างด้าวใช้สําเนาหนังสือเดินทางหรือใบสําคัญประจำตัวคนต่างด้าว).
        /// </summary>
        public static string IDENTITY_COPY {
            get {
                return ResourceManager.GetString("IDENTITY_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แผนที่ตั้งและภาพถ่ายของสถานประกอบการ.
        /// </summary>
        public static string MAP_AND_PHOTO_OF_ORGANIZATION {
            get {
                return ResourceManager.GetString("MAP_AND_PHOTO_OF_ORGANIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ระบุ.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หนังสือมอบอำนาจ.
        /// </summary>
        public static string POWER_OF_ATTORNEY_COPY {
            get {
                return ResourceManager.GetString("POWER_OF_ATTORNEY_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหนังสือสัญญาเช่า หรือหนังสือยินยอมให้ใช้สถานที่ หรือสัญญาเช่าแผง หรือหลักฐานแสดงเลขที่แผงและที่ตั้งของตลาด หรือห้างสรรพสินค้า.
        /// </summary>
        public static string RENTAL_AGREEMENT_COPY {
            get {
                return ResourceManager.GetString("RENTAL_AGREEMENT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สปส. 1-02.
        /// </summary>
        public static string SSO102 {
            get {
                return ResourceManager.GetString("SSO102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สปส. 1-03.
        /// </summary>
        public static string SSO103 {
            get {
                return ResourceManager.GetString("SSO103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สปส. 6-07.
        /// </summary>
        public static string SSO607 {
            get {
                return ResourceManager.GetString("SSO607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหรือภาพถ่าย บัตรประจำตัวผู้เสียภาษีอากร/ร.ง. 4/ภ.พ.20/ภ.ธ. 20.
        /// </summary>
        public static string TAX_IDENTITY_COPY {
            get {
                return ResourceManager.GetString("TAX_IDENTITY_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาหรือภาพถ่าย ภ.พ.01/ ภธ.20/ ใบอนุญาตประกอบธุรกิจของคนต่างด้าว.
        /// </summary>
        public static string TAX_IDENTITY_COPY_OR_FORGEIGN_BUSSINESS_LICENSE {
            get {
                return ResourceManager.GetString("TAX_IDENTITY_COPY_OR_FORGEIGN_BUSSINESS_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประชาชนไทย.
        /// </summary>
        public static string THAI_CITIZEN {
            get {
                return ResourceManager.GetString("THAI_CITIZEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สำเนาใบอนุญาติทำงานคนต่างด้าว.
        /// </summary>
        public static string WORK_PERMITTED_COPY {
            get {
                return ResourceManager.GetString("WORK_PERMITTED_COPY", resourceCulture);
            }
        }
    }
}
