//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermitSummary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermitSummary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.PermitSummary", typeof(PermitSummary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หากเป็นนิติบุคคล ไม่จำเป็นต้องจดทะเบียนพาณิชย์.
        /// </summary>
        public static string APP_WARNING_JURISTIC_NO_NEED_TRADER_REGISTRATION {
            get {
                return ResourceManager.GetString("APP_WARNING_JURISTIC_NO_NEED_TRADER_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลับหน้าแรก.
        /// </summary>
        public static string BTN_BACK_TO_HOME {
            get {
                return ResourceManager.GetString("BTN_BACK_TO_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอกลับไปเลือกใบอนุญาตใหม่.
        /// </summary>
        public static string BTN_BACK_TO_PERMIT_MENU {
            get {
                return ResourceManager.GetString("BTN_BACK_TO_PERMIT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขอกลับไปทำแบบสอบถามอีกครั้ง.
        /// </summary>
        public static string BTN_BACK_TO_QUIZ {
            get {
                return ResourceManager.GetString("BTN_BACK_TO_QUIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดำเนินการขอใบอนุญาตทันที.
        /// </summary>
        public static string BTN_GO_SINGLE_FORM {
            get {
                return ResourceManager.GetString("BTN_GO_SINGLE_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกใบอนุญาตที่คุณต้องการขอผ่าน Biz Portal จากทั้งหมด {0} รายการ.
        /// </summary>
        public static string HEADING_PERMIT_SUMMARY {
            get {
                return ResourceManager.GetString("HEADING_PERMIT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันใบอนุญาตที่คุณเลือก.
        /// </summary>
        public static string HEADING_SELECTED_APPS {
            get {
                return ResourceManager.GetString("HEADING_SELECTED_APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวม.
        /// </summary>
        public static string HEADING_SUMMARY {
            get {
                return ResourceManager.GetString("HEADING_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกใบอนุญาตที่คุณต้องยื่นคำขอ.
        /// </summary>
        public static string TEXT_APP_REQUIRED {
            get {
                return ResourceManager.GetString("TEXT_APP_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บาท.
        /// </summary>
        public static string TEXT_BAHT {
            get {
                return ResourceManager.GetString("TEXT_BAHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยื่นคำขอได้ที่.
        /// </summary>
        public static string TEXT_CAN_BE_REQUEST_AT {
            get {
                return ResourceManager.GetString("TEXT_CAN_BE_REQUEST_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน.
        /// </summary>
        public static string TEXT_DAYS {
            get {
                return ResourceManager.GetString("TEXT_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยื่นคำขอได้ที่ e-service หน่วยงาน.
        /// </summary>
        public static string TEXT_ESERVICE_URL {
            get {
                return ResourceManager.GetString("TEXT_ESERVICE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดูรายละเอียด.
        /// </summary>
        public static string TEXT_MORE_DETAIL {
            get {
                return ResourceManager.GetString("TEXT_MORE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จะเปิดให้บริการยื่นคำขอผ่าน Biz Portal ได้ในเร็วๆนี้.
        /// </summary>
        public static string TEXT_OPEN_SOON {
            get {
                return ResourceManager.GetString("TEXT_OPEN_SOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เริ่มต้นที่.
        /// </summary>
        public static string TEXT_STARTING_AT {
            get {
                return ResourceManager.GetString("TEXT_STARTING_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวม.
        /// </summary>
        public static string TEXT_SUMMARY_TOTAL_COST {
            get {
                return ResourceManager.GetString("TEXT_SUMMARY_TOTAL_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมวันทำการ.
        /// </summary>
        public static string TEXT_SUMMARY_TOTAL_DAYS {
            get {
                return ResourceManager.GetString("TEXT_SUMMARY_TOTAL_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปค่าธรรมเนียม และระยะเวลาที่คาดว่าจะดำเนินการเสร็จสิ้น.
        /// </summary>
        public static string TITLE_CONFIRM_PERMIT_SUMMARY {
            get {
                return ResourceManager.GetString("TITLE_CONFIRM_PERMIT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบ และยืนยันความถูกต้องของข้อมูลคำขอ.
        /// </summary>
        public static string TITLE_CONFIRMATION {
            get {
                return ResourceManager.GetString("TITLE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * ค่าธรรมเนียมอาจมีการเปลี่ยนแปลงตามอัตราที่หน่วยงานประกาศกำหนด.
        /// </summary>
        public static string TITLE_FEE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TITLE_FEE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สรุปใบอนุญาตที่คุณต้องขอ.
        /// </summary>
        public static string TITLE_PERMIT_SUMMARY {
            get {
                return ResourceManager.GetString("TITLE_PERMIT_SUMMARY", resourceCulture);
            }
        }
    }
}
