//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Quiz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Quiz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.Quiz", typeof(Quiz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำเข้าสินค้าตาม 5  ประเภทข้างบน.
        /// </summary>
        public static string ALL_5_DOMESTIC_GOODS {
            get {
                return ResourceManager.GetString("ALL_5_DOMESTIC_GOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1 ธุรกิจของคุณเข้าข่ายประเภทกิจการใดบ้าง (เลือกได้มากกว่า 1 ข้อ).
        /// </summary>
        public static string BUSINESS_GOODS_TYPE {
            get {
                return ResourceManager.GetString("BUSINESS_GOODS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1 ธุรกิจของคุณเข้าข่ายประเภทกิจการใดบ้าง (เลือกได้มากกว่า 1 ข้อ).
        /// </summary>
        public static string BUSINESS_SERVICES_TYPE {
            get {
                return ResourceManager.GetString("BUSINESS_SERVICES_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขาย ให้เช่า ผลิต แผ่นซีดี แถบบันทึก วีดิทัศน์ แผ่นวีดิทัศน์ ดีวีดี หรือแผ่นวีดิทัศน์ระบบดิจิทัล.
        /// </summary>
        public static string CDS_DVDS_TAPES_FOR_SELL_OR_RENT {
            get {
                return ResourceManager.GetString("CDS_DVDS_TAPES_FOR_SELL_OR_RENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการจัดแข่งขันกีฬาสมัครเล่น.
        /// </summary>
        public static string COMPETITIVE_SPORTS_SERVICE {
            get {
                return ResourceManager.GetString("COMPETITIVE_SPORTS_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการแสดงศิลปวัฒนธรรม ได้แก่ การแสดงพื้นเมือง ระบำ ละคร และโขน หรือการแสดงดนตรีไทยและไม่ได้เรียกเก็บค่าบริการโดยตรงจากผู้ชม.
        /// </summary>
        public static string CULTURAL_AND_ART_SERVICES {
            get {
                return ResourceManager.GetString("CULTURAL_AND_ART_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการตลาดกลางผ่านอินเทอร์เน็ต บริการอินเทอร์เน็ต ให้เช่าเครื่องคอมพิวเตอร์ หรือให้เช่าพื้นที่เครื่องคอมพิวเตอร์แม่ข่าย.
        /// </summary>
        public static string DATACENTER_AND_HOST_SERVICES {
            get {
                return ResourceManager.GetString("DATACENTER_AND_HOST_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายสินค้า หรือการให้บริการอื่นๆตามที่กำหนดโดยพระราชกฤษฎีกาฯ (ฉบับที่ 239) พ.ศ.2534.
        /// </summary>
        public static string DECREE_NO239_GOODS_AND_SERVICES {
            get {
                return ResourceManager.GetString("DECREE_NO239_GOODS_AND_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายพืชผลทางการเกษตรแบบสด ภายในประเทศ เช่น ข้าว ข้าวโพด มันสำปะหลัง ผัก ผลไม้ เป็นต้น.
        /// </summary>
        public static string DOMESTIC_AGRICULTURAL_CROPS {
            get {
                return ResourceManager.GetString("DOMESTIC_AGRICULTURAL_CROPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายปลาป่น หรืออาหารสัตว์ ภายในประเทศ.
        /// </summary>
        public static string DOMESTIC_ANIMAL_FOODS {
            get {
                return ResourceManager.GetString("DOMESTIC_ANIMAL_FOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายสัตว์มีชีวิต หนังสัตว์ที่ยังไม่ได้ฟอก และเนื้อสัตว์ที่ยังไม่ได้แปรรูป ภายในประเทศ.
        /// </summary>
        public static string DOMESTIC_ANIMALS_AND_UNPROCESSED_MEAT {
            get {
                return ResourceManager.GetString("DOMESTIC_ANIMALS_AND_UNPROCESSED_MEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายปุ๋ย เคมีภัณฑ์ หรือยาสำหรับใช้ในพืชและสัตว์ ภายในประเทศ.
        /// </summary>
        public static string DOMESTIC_FERTILIZERS_CHEMICALS_MEDICINES {
            get {
                return ResourceManager.GetString("DOMESTIC_FERTILIZERS_CHEMICALS_MEDICINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการการขนส่งน้ำมันเชื้อเพลิงทางท่อภายในประเทศ.
        /// </summary>
        public static string DOMESTIC_FUEL_TRANSPORTATION {
            get {
                return ResourceManager.GetString("DOMESTIC_FUEL_TRANSPORTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายหนังสือพิมพ์ นิตยสาร หรือตำราเรียน ภายในประเทศ.
        /// </summary>
        public static string DOMESTIC_NEWSPAPER_MAGAZINES_AND_TEXTBOOKS {
            get {
                return ResourceManager.GetString("DOMESTIC_NEWSPAPER_MAGAZINES_AND_TEXTBOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการขนส่งภายในประเทศโดยอากาศยาน.
        /// </summary>
        public static string DOMESTIC_TRANSPORTATION_BY_AIR {
            get {
                return ResourceManager.GetString("DOMESTIC_TRANSPORTATION_BY_AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการขนส่งภายในประเทศไม่ว่าจะเป็นทางบกหรือทางน้ำ.
        /// </summary>
        public static string DOMESTIC_TRANSPORTATION_BY_LANDWATER {
            get {
                return ResourceManager.GetString("DOMESTIC_TRANSPORTATION_BY_LANDWATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการด้านการศึกษาของสถานศึกษารัฐและเอกชน.
        /// </summary>
        public static string EDUCATIONAL_SERVICES {
            get {
                return ResourceManager.GetString("EDUCATIONAL_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายสินค้าส่งออก โดยดำเนินการในเขตอุตสาหกรรมส่งออกของนิคมอุตสาหกรรม.
        /// </summary>
        public static string EXPORTED_GOODS_BY_INDUSTRIAL_PARK {
            get {
                return ResourceManager.GetString("EXPORTED_GOODS_BY_INDUSTRIAL_PARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายอัญมณี หรือเครื่องประดับอัญมณี.
        /// </summary>
        public static string GEMSTONE_AND_JEWELRY {
            get {
                return ResourceManager.GetString("GEMSTONE_AND_JEWELRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายสินค้าอื่นๆนอกเหนือจากที่ระบุข้างต้น.
        /// </summary>
        public static string GOOD_TYPES_ETC {
            get {
                return ResourceManager.GetString("GOOD_TYPES_ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายสินค้าหรือการให้บริการของกระทรวง ทบวง กรม ซึ่งส่งรายรับทั้งสิ้นให้แก่รัฐโดยไม่หักรายจ่าย.
        /// </summary>
        public static string GOODS_AND_SERVICES_FOR_MINISTRY {
            get {
                return ResourceManager.GetString("GOODS_AND_SERVICES_FOR_MINISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. ท่านมีเลขประจำบ้าน 11 หลักแล้วหรือยัง.
        /// </summary>
        public static string HAS_HOME_NUMBER {
            get {
                return ResourceManager.GetString("HAS_HOME_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. ธุรกิจของคุณขายสินค้าหรือให้บริการผ่านอินเทอร์เน็ตหรือไม่.
        /// </summary>
        public static string HAS_ONLINE_STORE {
            get {
                return ResourceManager.GetString("HAS_ONLINE_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ ฉันไม่ได้ทำธุรกิจผ่านอินเทอร์เน็ต.
        /// </summary>
        public static string HAS_ONLINE_STORE_NO {
            get {
                return ResourceManager.GetString("HAS_ONLINE_STORE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช่ ฉันทำธุรกิจโดยใช้อินเตอร์เน็ต.
        /// </summary>
        public static string HAS_ONLINE_STORE_YES {
            get {
                return ResourceManager.GetString("HAS_ONLINE_STORE_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการรักษาพยาบาลของสถานพยาบาลรัฐและเอกชน.
        /// </summary>
        public static string HOSPITAL_SERVICES {
            get {
                return ResourceManager.GetString("HOSPITAL_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. ประเภทการติดตั้ง.
        /// </summary>
        public static string INSTALL_TYPE {
            get {
                return ResourceManager.GetString("INSTALL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการขนส่งระหว่างประเทศทางบกและทางเรือซึ่งมิใช่เรือเดินทะเล.
        /// </summary>
        public static string INTERNATIONAL_SHIPPING_BY_LANDWATER {
            get {
                return ResourceManager.GetString("INTERNATIONAL_SHIPPING_BY_LANDWATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. กิจการของคุณมีการให้บริการหรือไม่.
        /// </summary>
        public static string IS_BUSINESS_PROVIDE_SERVICES {
            get {
                return ResourceManager.GetString("IS_BUSINESS_PROVIDE_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ กิจการของฉันไม่มีการให้บริการ.
        /// </summary>
        public static string IS_BUSINESS_PROVIDE_SERVICES_NO {
            get {
                return ResourceManager.GetString("IS_BUSINESS_PROVIDE_SERVICES_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช่ กิจการของฉันมีการให้บริการ.
        /// </summary>
        public static string IS_BUSINESS_PROVIDE_SERVICES_YES {
            get {
                return ResourceManager.GetString("IS_BUSINESS_PROVIDE_SERVICES_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. กิจการของคุณมีการค้าขายสินค้าหรือไม่.
        /// </summary>
        public static string IS_BUSINESS_SELLING_GOODS {
            get {
                return ResourceManager.GetString("IS_BUSINESS_SELLING_GOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ กิจการของฉันไม่มีการค้าขายสินค้า.
        /// </summary>
        public static string IS_BUSINESS_SELLING_GOODS_NO {
            get {
                return ResourceManager.GetString("IS_BUSINESS_SELLING_GOODS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช่ กิจการของฉันมีการค้าขายสินค้า.
        /// </summary>
        public static string IS_BUSINESS_SELLING_GOODS_YES {
            get {
                return ResourceManager.GetString("IS_BUSINESS_SELLING_GOODS_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3 ประเภทกิจการของคุณ “ไม่เข้าข่าย” ที่ต้องจดทะเบียนภาษีมูลค่าเพิ่ม แต่คุณสามารถจดทะเบียนภาษีมูลค่าเพิ่มได้.
        /// </summary>
        public static string IS_NEED_VAT {
            get {
                return ResourceManager.GetString("IS_NEED_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ ฉันยังไม่ต้องการจดทะเบียนภาษีมูลค่าเพิ่มตอนนี้.
        /// </summary>
        public static string IS_NEED_VAT_NO {
            get {
                return ResourceManager.GetString("IS_NEED_VAT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช่ ฉันต้องการจดทะเบียนภาษีมูลค่าเพิ่ม.
        /// </summary>
        public static string IS_NEED_VAT_YES {
            get {
                return ResourceManager.GetString("IS_NEED_VAT_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. คุณได้จดทะเบียนนิติบุคคลกับกรมพัฒนาธุรกิจการค้าจนเสร็จสิ้นแล้วหรือไม่.
        /// </summary>
        public static string IS_REGISTERED_JURISTIC {
            get {
                return ResourceManager.GetString("IS_REGISTERED_JURISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ ฉันยังไม่ได้จดทะเบียนนิติบุคคล.
        /// </summary>
        public static string IS_REGISTERED_JURISTIC_NO {
            get {
                return ResourceManager.GetString("IS_REGISTERED_JURISTIC_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช่ ฉันจดทะเบียนนิติบุคคลแล้ว.
        /// </summary>
        public static string IS_REGISTERED_JURISTIC_YES {
            get {
                return ResourceManager.GetString("IS_REGISTERED_JURISTIC_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายงาช้างและผลิตภัณฑ์ที่เกี่ยวข้อง หรือแปรสภาพ แกะสลัก และทำหัตถกรรมจากงาช้าง.
        /// </summary>
        public static string IVORY_AND_CARVED_IVORY {
            get {
                return ResourceManager.GetString("IVORY_AND_CARVED_IVORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการคาราโอเกะ เครื่องเล่นเกมส์ หรือตู้เพลง.
        /// </summary>
        public static string KARAOKE_GAME_CONSOLE_SERVICES {
            get {
                return ResourceManager.GetString("KARAOKE_GAME_CONSOLE_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการตามสัญญาจ้างแรงงาน.
        /// </summary>
        public static string LABOR_CONTRACT_SERVICES {
            get {
                return ResourceManager.GetString("LABOR_CONTRACT_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการห้องสมุด พิพิธภัณฑ์ สวนสัตว์.
        /// </summary>
        public static string LIBRARY_MUSEUM_ZOO {
            get {
                return ResourceManager.GetString("LIBRARY_MUSEUM_ZOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการประกอบโรคศิลปะ การสอบบัญชี การว่าความ.
        /// </summary>
        public static string MEDICAL_TREATMENT_AUDIT_AND_LAWYER {
            get {
                return ResourceManager.GetString("MEDICAL_TREATMENT_AUDIT_AND_LAWYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. สถานที่ที่ต้องการขอติดตั้งสาธารณูปโภคอยู่ภายในเขต.
        /// </summary>
        public static string METRO_OR_PROVINCE {
            get {
                return ResourceManager.GetString("METRO_OR_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. ธุรกิจของคุณมีลูกจ้างกี่คน.
        /// </summary>
        public static string NUMBER_OF_EMPLOYEES {
            get {
                return ResourceManager.GetString("NUMBER_OF_EMPLOYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีลูกจ้าง 1-9 คน.
        /// </summary>
        public static string NUMBER_OF_EMPLOYEES_1_TO_9 {
            get {
                return ResourceManager.GetString("NUMBER_OF_EMPLOYEES_1_TO_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีลูกจ้าง 10 คนขึ้นไป.
        /// </summary>
        public static string NUMBER_OF_EMPLOYEES_MORETHAN_10 {
            get {
                return ResourceManager.GetString("NUMBER_OF_EMPLOYEES_MORETHAN_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่มีลูกจ้าง.
        /// </summary>
        public static string NUMBER_OF_EMPLOYEES_NO {
            get {
                return ResourceManager.GetString("NUMBER_OF_EMPLOYEES_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ให้บริการเช่าอสังหาริมทรัพย์.
        /// </summary>
        public static string REAL_ESTATE_REANTAL_SERVICE {
            get {
                return ResourceManager.GetString("REAL_ESTATE_REANTAL_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขายสินค้าหรือการให้บริการเพื่อประโยชน์แก่การศาสนา หรือการสาธารณกุศลภายในประเทศ ซึ่งไม่นำผลกำไรไปจ่ายในทางอื่น.
        /// </summary>
        public static string RELIGION_AND_DOMESTIC_CHARITY {
            get {
                return ResourceManager.GetString("RELIGION_AND_DOMESTIC_CHARITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่นๆ นอกเหนือจากที่ระบุข้างต้น.
        /// </summary>
        public static string SERVICE_TYPES_ETC {
            get {
                return ResourceManager.GetString("SERVICE_TYPES_ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2 ธุรกิจของคุณดังต่อไปนี้....
        /// </summary>
        public static string SPECIAL_ANNUAL_REVENUE_18_1 {
            get {
                return ResourceManager.GetString("SPECIAL_ANNUAL_REVENUE_18_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีรายรับรวมเกิน 1.8 ล้านบาทต่อปีใช่หรือไม่.
        /// </summary>
        public static string SPECIAL_ANNUAL_REVENUE_18_2 {
            get {
                return ResourceManager.GetString("SPECIAL_ANNUAL_REVENUE_18_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ ฉันยังมีรายรับไม่ถึง 1.8 ล้านบาทต่อปี.
        /// </summary>
        public static string SPECIAL_ANNUAL_REVENUE_18_NO {
            get {
                return ResourceManager.GetString("SPECIAL_ANNUAL_REVENUE_18_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช่ ฉันมีรายรับรวมเกิน 1.8 ล้านบาทต่อปี.
        /// </summary>
        public static string SPECIAL_ANNUAL_REVENUE_18_YES {
            get {
                return ResourceManager.GetString("SPECIAL_ANNUAL_REVENUE_18_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบสอบถามการขอติดตั้งสาธารณูปโภค.
        /// </summary>
        public static string TITLE_UTILITIES {
            get {
                return ResourceManager.GetString("TITLE_UTILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. บริการที่ต้องการขอติดตั้ง.
        /// </summary>
        public static string UTILITY_SERVICES {
            get {
                return ResourceManager.GetString("UTILITY_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ {
            get {
                return ResourceManager.GetString("ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ", resourceCulture);
            }
        }
    }
}
