//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.Report", typeof(Report).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำขอที่อยู่ระหว่างดำเนินการ.
        /// </summary>
        public static string onProcessRequestSummary_Header {
            get {
                return ResourceManager.GetString("onProcessRequestSummary_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เดือน (Month).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_ByMonth {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_ByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไตรมาส (Quarter).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_ByQuater {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_ByQuater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มกราคม (JAN).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption1 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตุลาคม (OCT).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption10 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พฤศจิกายน (NOV).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption11 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ธันวาคม (DEC).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption12 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กุมภาพันธ์ (FEB).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption2 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีนาคม (MAR).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption3 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เมษายน (APR).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption4 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พฤษภาคม (MAY).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption5 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มิถุนายน (JUN).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption6 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรกฎาคม (JUL).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption7 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สิงหาคม (AUG).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption8 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กันยายน (SEP).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOption9 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOption9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด (All).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_MonthOrQuaterPlaceHolder {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_MonthOrQuaterPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไตรมาสที่ 1 (Q1).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_QuaterOption1 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_QuaterOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไตรมาสที่ 2 (Q2).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_QuaterOption2 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_QuaterOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไตรมาสที่ 3 (Q3).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_QuaterOption3 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_QuaterOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไตรมาสที่ 4 (Q4).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_QuaterOption4 {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_QuaterOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาพรวมธุรกิจที่ได้รับความนิยมสูงสุดในการขอใบอนุญาต.
        /// </summary>
        public static string PermitRequestSummaryByBusiness_Title {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด (All).
        /// </summary>
        public static string PermitRequestSummaryByBusiness_YearPlaceHolder {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByBusiness_YearPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แนวโน้มการขอใบอนุญาตแบ่งตามช่วงเวลา.
        /// </summary>
        public static string PermitRequestSummaryByMoment_Title {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByMoment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แนวโน้มการขอใบอนุญาตแบ่งตามเขตจังหวัด.
        /// </summary>
        public static string PermitRequestSummaryByProvince_Title {
            get {
                return ResourceManager.GetString("PermitRequestSummaryByProvince_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันให้บริการโดยเฉลี่ย (วัน).
        /// </summary>
        public static string Statistics_Average_Operation_Days_Average_Operation_Days {
            get {
                return ResourceManager.GetString("Statistics_Average_Operation_Days_Average_Operation_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรวจสอบคำขอเบื้องต้น.
        /// </summary>
        public static string Statistics_Average_Operation_Days_Check {
            get {
                return ResourceManager.GetString("Statistics_Average_Operation_Days_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชำระค่าธรรมเนียม.
        /// </summary>
        public static string Statistics_Average_Operation_Days_Paid_Fee {
            get {
                return ResourceManager.GetString("Statistics_Average_Operation_Days_Paid_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิจารณา.
        /// </summary>
        public static string Statistics_Average_Operation_Days_Pending {
            get {
                return ResourceManager.GetString("Statistics_Average_Operation_Days_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกใบอนุญาต.
        /// </summary>
        public static string Statistics_Average_Operation_Days_Publish_License {
            get {
                return ResourceManager.GetString("Statistics_Average_Operation_Days_Publish_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคำขอที่ถูกปฏิเสธ ณ ขั้นตอน (คำขอ).
        /// </summary>
        public static string Statistics_Average_Operation_Days_Rejected_Request {
            get {
                return ResourceManager.GetString("Statistics_Average_Operation_Days_Rejected_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขั้นตอน.
        /// </summary>
        public static string Statistics_Average_Operation_Days_Status {
            get {
                return ResourceManager.GetString("Statistics_Average_Operation_Days_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผลลัพท์การให้บริการ แบ่งตามขั้นตอน.
        /// </summary>
        public static string Statistics_Average_Operation_Days_Title {
            get {
                return ResourceManager.GetString("Statistics_Average_Operation_Days_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถิติคำขออนุญาต (Request Statistics).
        /// </summary>
        public static string Statistics_Header {
            get {
                return ResourceManager.GetString("Statistics_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บุคคลธรรมดา.
        /// </summary>
        public static string Statistics_Identity_Type_Citizen {
            get {
                return ResourceManager.GetString("Statistics_Identity_Type_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นิติบุคคล.
        /// </summary>
        public static string Statistics_Identity_Type_Juristic {
            get {
                return ResourceManager.GetString("Statistics_Identity_Type_Juristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบ่งตามหน่วยงาน.
        /// </summary>
        public static string Statistics_Identity_Type_Request_Organization {
            get {
                return ResourceManager.GetString("Statistics_Identity_Type_Request_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คิดเป็นสัดส่วนระหว่างกลุ่มผู้ใช้ (%).
        /// </summary>
        public static string Statistics_Identity_Type_Request_Pencentage {
            get {
                return ResourceManager.GetString("Statistics_Identity_Type_Request_Pencentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบ่งตามใบอนุญาต.
        /// </summary>
        public static string Statistics_Identity_Type_Request_PermitName {
            get {
                return ResourceManager.GetString("Statistics_Identity_Type_Request_PermitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนใบอนุญาต (ใบ).
        /// </summary>
        public static string Statistics_Identity_Type_Request_Total {
            get {
                return ResourceManager.GetString("Statistics_Identity_Type_Request_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคำขอแบ่งตามหน่วยงาน (บุคคลธรรมดา).
        /// </summary>
        public static string Statistics_Organization_By_Citizen {
            get {
                return ResourceManager.GetString("Statistics_Organization_By_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคำขอแบ่งตามหน่วยงาน (นิติบุคคล).
        /// </summary>
        public static string Statistics_Organization_By_Juristic {
            get {
                return ResourceManager.GetString("Statistics_Organization_By_Juristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนใบอนุญาต (ใบ).
        /// </summary>
        public static string Statistics_Organization_Request_Qty {
            get {
                return ResourceManager.GetString("Statistics_Organization_Request_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำขอทั้งหมด (คำขอ).
        /// </summary>
        public static string Statistics_Overall_All_Permit {
            get {
                return ResourceManager.GetString("Statistics_Overall_All_Permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งแต่ 1 ม.ค. ของปีที่เลือก.
        /// </summary>
        public static string Statistics_Overall_At_First_Day_Of_Year {
            get {
                return ResourceManager.GetString("Statistics_Overall_At_First_Day_Of_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เดือนล่าสุด.
        /// </summary>
        public static string Statistics_Overall_At_Latest_Month {
            get {
                return ResourceManager.GetString("Statistics_Overall_At_Latest_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งแต่เปิดศูนย์ฯ.
        /// </summary>
        public static string Statistics_Overall_At_Start {
            get {
                return ResourceManager.GetString("Statistics_Overall_At_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิจารณาเสร็จสิ้น (คำขอ).
        /// </summary>
        public static string Statistics_Overall_Done {
            get {
                return ResourceManager.GetString("Statistics_Overall_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คิดเป็น (%).
        /// </summary>
        public static string Statistics_Overall_Done_2 {
            get {
                return ResourceManager.GetString("Statistics_Overall_Done_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าธรรมเนียม (บาท).
        /// </summary>
        public static string Statistics_Overall_Fee {
            get {
                return ResourceManager.GetString("Statistics_Overall_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาพรวมสถิติคำขอ.
        /// </summary>
        public static string Statistics_Overall_header {
            get {
                return ResourceManager.GetString("Statistics_Overall_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำขอที่พิจารณาทันกำหนด (%).
        /// </summary>
        public static string Statistics_Overall_InTime_SLA {
            get {
                return ResourceManager.GetString("Statistics_Overall_InTime_SLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังดำเนินการ (คำขอ).
        /// </summary>
        public static string Statistics_Overall_OnProcess {
            get {
                return ResourceManager.GetString("Statistics_Overall_OnProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คิดเป็น (%).
        /// </summary>
        public static string Statistics_Overall_OnProcess_2 {
            get {
                return ResourceManager.GetString("Statistics_Overall_OnProcess_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคำขอแบ่งตามชื่อใบอนุญาต (บุคคลธรรมดา).
        /// </summary>
        public static string Statistics_Permitname_By_Citizen {
            get {
                return ResourceManager.GetString("Statistics_Permitname_By_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคำขอแบ่งตามชื่อใบอนุญาต (นิติบุคคล).
        /// </summary>
        public static string Statistics_Permitname_By_Juristic {
            get {
                return ResourceManager.GetString("Statistics_Permitname_By_Juristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนใบอนุญาต (ใบ).
        /// </summary>
        public static string Statistics_Permitname_Request_Qty {
            get {
                return ResourceManager.GetString("Statistics_Permitname_Request_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกอำเภอ/เขต.
        /// </summary>
        public static string Statistics_Query_District {
            get {
                return ResourceManager.GetString("Statistics_Query_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกเดือน.
        /// </summary>
        public static string Statistics_Query_Month {
            get {
                return ResourceManager.GetString("Statistics_Query_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกหน่วยงาน.
        /// </summary>
        public static string Statistics_Query_Organization {
            get {
                return ResourceManager.GetString("Statistics_Query_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกใบอนุญาต.
        /// </summary>
        public static string Statistics_Query_Permit {
            get {
                return ResourceManager.GetString("Statistics_Query_Permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกจังหวัด.
        /// </summary>
        public static string Statistics_Query_Province {
            get {
                return ResourceManager.GetString("Statistics_Query_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกประเภทผู้ยื่นคำขอ.
        /// </summary>
        public static string Statistics_Query_Requestor_Type {
            get {
                return ResourceManager.GetString("Statistics_Query_Requestor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลือกปี.
        /// </summary>
        public static string Statistics_Query_Year {
            get {
                return ResourceManager.GetString("Statistics_Query_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคำขอ แบ่งตามกลุ่มผู้ใช้.
        /// </summary>
        public static string Statistics_Request_By_Identity_Type_header {
            get {
                return ResourceManager.GetString("Statistics_Request_By_Identity_Type_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำขอที่พิจารณาเสร็จสิ้น แบ่งตามความเร่งด่วน.
        /// </summary>
        public static string Statistics_SLA_Done_Request_header {
            get {
                return ResourceManager.GetString("Statistics_SLA_Done_Request_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทันกำหนด.
        /// </summary>
        public static string Statistics_SLA_Done_Request_InTime {
            get {
                return ResourceManager.GetString("Statistics_SLA_Done_Request_InTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ทันกำหนด.
        /// </summary>
        public static string Statistics_SLA_Done_Request_OutTime {
            get {
                return ResourceManager.GetString("Statistics_SLA_Done_Request_OutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคำขอแบ่งตามสถานะ SLA.
        /// </summary>
        public static string Statistics_SLA_Status_header {
            get {
                return ResourceManager.GetString("Statistics_SLA_Status_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทันกำหนด.
        /// </summary>
        public static string Statistics_SLA_Status_InTime_SLA {
            get {
                return ResourceManager.GetString("Statistics_SLA_Status_InTime_SLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่เริ่มนับ SLA.
        /// </summary>
        public static string Statistics_SLA_Status_Not_Start_SLA {
            get {
                return ResourceManager.GetString("Statistics_SLA_Status_Not_Start_SLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ทันกำหนด.
        /// </summary>
        public static string Statistics_SLA_Status_OutTime_SLA {
            get {
                return ResourceManager.GetString("Statistics_SLA_Status_OutTime_SLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคำขอแบ่งตามสถานะ SLA.
        /// </summary>
        public static string Statistics_SLA_Status_Title {
            get {
                return ResourceManager.GetString("Statistics_SLA_Status_Title", resourceCulture);
            }
        }
    }
}
