//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tracking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tracking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizPortal.Resources.Tracking", typeof(Tracking).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน่วยงาน.
        /// </summary>
        public static string ANGENCY {
            get {
                return ResourceManager.GetString("ANGENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันคำขอ.
        /// </summary>
        public static string BTN_CONFIRM_REQUEST {
            get {
                return ResourceManager.GetString("BTN_CONFIRM_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่คาดว่าจะแล้วเสร็จ จะปรากฏต่อเมื่อเจ้าหน้าที่ได้อนุมัติขั้นตอน &quot;ตรวจสอบคำขอเบื้องต้น&quot; แล้ว.
        /// </summary>
        public static string EXPECTED_DATE_REMARK {
            get {
                return ResourceManager.GetString("EXPECTED_DATE_REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่คาดว่าจะแล้วเสร็จ จะปรากฏต่อเมื่อเจ้าหน้าที่ได้อนุมัติขั้นตอน “ตรวจสอบคำขอเบื้องต้น” แล้ว.
        /// </summary>
        public static string EXPECTED_DATE_REMARK_NOT_YET {
            get {
                return ResourceManager.GetString("EXPECTED_DATE_REMARK_NOT_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริการ.
        /// </summary>
        public static string SERVICE {
            get {
                return ResourceManager.GetString("SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะคำร้อง.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ทำรายการ.
        /// </summary>
        public static string SUBMISSION_DATE {
            get {
                return ResourceManager.GetString("SUBMISSION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะการยืนคำร้อง หมายเลข {0}.
        /// </summary>
        public static string TRACKING_TITLE {
            get {
                return ResourceManager.GetString("TRACKING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ปรับปรุง.
        /// </summary>
        public static string UPDATE_DATE {
            get {
                return ResourceManager.GetString("UPDATE_DATE", resourceCulture);
            }
        }
    }
}
