using BizPortal.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Globalization;
using System.Linq;
using System.Configuration;

namespace BizPortal.DAL.Seeds
{
    public class _20181214_PaymentSeed
    {
        public static void Seed(BizPortal.DAL.ApplicationDbContext context, ApplicationUser adminUser)
        {
            if (ConfigurationManager.AppSettings["TestMode"] == "true")
            {
                // สบส.
                var paymentCenters = new List<PaymentCenter>
                {
                    new PaymentCenter
                    {
                        PaymentCenterCode = "2100700004",
                        Description = "กองคลัง",
                        ShortDescription ="กองคลัง",
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now
                    }
                };

                context.PaymentCenters.AddOrUpdate(o => o.PaymentCenterCode, paymentCenters.ToArray());
                context.SaveChanges(false);

                var costCenters = new List<PaymentHomeCostCenter>()
                {
                    new PaymentHomeCostCenter
                    {
                        PaymentOrgCode="21007",
                        CostCenterCode="2100700004",
                        StartDate=DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate=null,
                        ProvinceCode="1000",
                        Name="กองคลัง",
                        Description="กรมสนับสนุนบริการสุขภาพ",
                        PaymentCenterID = paymentCenters.Where(e=>e.PaymentCenterCode == "2100700004").SingleOrDefault().PaymentCenterID,
                        CreatedUserID = adminUser.Id,
                        CreatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now
                    }
                };

                context.PaymentHomeCostCenters.AddOrUpdate(o => o.CostCenterCode, costCenters.ToArray());
                context.SaveChanges(false);

                var paymentCatalogs = new List<PaymentCatalog>
                {
                    new PaymentCatalog
                    {
                        Order = 1,
                        PaymentCatalogCode = "2100700066",
                        Description = "ค่าธรรมเนียมการประกอบกิจการคลีนิก รายปี",
                        Amount = 500,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2022-10-22","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 1,
                        PaymentCatalogCode = "2100700067",
                        Description = "ค่าธรรมเนียมใบอนุญาตให้ดำเนินการคลินิก",
                        Amount = 250,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2022-10-22","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 1,
                        PaymentCatalogCode = "2100700068",
                        Description = "ขออนุญาตให้ประกอบกิจการสถานพยาบาล (คลินิก)",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2022-10-22","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    }
                };

                context.PaymentCatalogs.AddOrUpdate(o => o.PaymentCatalogCode, paymentCatalogs.ToArray());
                context.SaveChanges(false);
            }
            else
            {
                // สบส.
                var paymentCenters = new List<PaymentCenter>
                {
                    new PaymentCenter
                    {
                        PaymentCenterCode = "2100700004",
                        Description = "กองคลัง",
                        ShortDescription ="กองคลัง",
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now
                    }
                };

                context.PaymentCenters.AddOrUpdate(o => o.PaymentCenterCode, paymentCenters.ToArray());
                context.SaveChanges(false);

                var costCenters = new List<PaymentHomeCostCenter>()
                {
                    new PaymentHomeCostCenter
                    {
                        PaymentOrgCode="21007",
                        CostCenterCode="2100700004",
                        StartDate=DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate=null,
                        ProvinceCode="1000",
                        Name="กองคลัง",
                        Description="กรมสนับสนุนบริการสุขภาพ",
                        PaymentCenterID = paymentCenters.Where(e=>e.PaymentCenterCode == "2100700004").SingleOrDefault().PaymentCenterID,
                        CreatedUserID = adminUser.Id,
                        CreatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now
                    }
                };

                context.PaymentHomeCostCenters.AddOrUpdate(o => o.CostCenterCode, costCenters.ToArray());
                context.SaveChanges(false);

                var paymentCatalogs = new List<PaymentCatalog>
                {
                    new PaymentCatalog
                    {
                        Order = 1,
                        PaymentCatalogCode = "2100700066",
                        Description = "ค่าธรรมเนียมใบอนญาตประกอบกิจการสปาไม่เกิน 100 ตร.ม.",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-11-01","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 2,
                        PaymentCatalogCode = "2100700031",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสปา ไม่เกิน 200 ตร.ม.",
                        Amount = 3000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 3,
                        PaymentCatalogCode = "2100700032",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสปา ไม่เกิน 400 ตร.ม.",
                        Amount = 6000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 4,
                        PaymentCatalogCode = "2100700033",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสปา เกิน 400 ตร.ม.",
                        Amount = 10000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 5,
                        PaymentCatalogCode = "2100700034",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสถานพยาบาล ไม่เกิน 10 เตียง",
                        Amount = 2000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 6,
                        PaymentCatalogCode = "2100700036",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสถานพยาบาล ไม่เกิน 10-25 เตียง",
                        Amount = 5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 7,
                        PaymentCatalogCode = "2100700038",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสถานพยาบาล ไม่เกิน 25-50 เตียง",
                        Amount = 10000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 8,
                        PaymentCatalogCode = "2100700040",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสถานพยาบาล ไม่เกิน 50-100 เตียง",
                        Amount = 20000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 9,
                        PaymentCatalogCode = "2100700042",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสถานพยาบาล  เกิน 100 เตียง",
                        Amount = 20000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 10,
                        PaymentCatalogCode = "2100700035",
                        Description = "ค่าธรรมเนียมใบอนุญาตดำเนินการสถานพยาบาล ไม่เกิน 10 เตียง",
                        Amount = 500,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 11,
                        PaymentCatalogCode = "2100700037",
                        Description = "ค่าธรรมเนียมใบอนุญาตดำเนินการสถานพยาบาล ไม่เกิน 10-25 เตียง",
                        Amount = 1250,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 12,
                        PaymentCatalogCode = "2100700039",
                        Description = "ค่าธรรมเนียมใบอนุญาตดำเนินการสถานพยาบาล ไม่เกิน 25-50 เตียง",
                        Amount = 2500,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 13,
                        PaymentCatalogCode = "2100700041",
                        Description = "ค่าธรรมเนียมใบอนุญาตดำเนินการสถานพยาบาล ไม่เกิน 50-100 เตียง",
                        Amount = 5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 14,
                        PaymentCatalogCode = "2100700043",
                        Description = "ค่าธรรมเนียมใบอนุญาตดำเนินการสถานพยาบาล เกิน 100 เตียง",
                        Amount = 5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 15,
                        PaymentCatalogCode = "2100700044",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการสถานพยาบาล 101 เตียง ขึ้นไป",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 16,
                        PaymentCatalogCode = "2100700045",
                        Description = "ค่าธรรมเนียมใบอนุญาตดำเนินการสถานพยาบาล 101 เตียง ขึ้นไป",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 17,
                        PaymentCatalogCode = "2100700046",
                        Description = "ค่าธรรมเนียมใบอนุญาตประกอบกิจการคลินิก",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 18,
                        PaymentCatalogCode = "2100700047",
                        Description = "ค่าธรรมเนียมใบอนุญาตให้ดำเนินการคลินิก",
                        Amount = 250,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-10-18","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 19,
                        PaymentCatalogCode = "2100700117",
                        Description = "ค่าธรรมเนียมการเปลี่ยนแปลงแก้ไขรายการในใบอนุญาต",
                        Amount = 300,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 20,
                        PaymentCatalogCode = "2100700092",
                        Description = "ค่าเปลี่ยนแปลงการประกอบกิจการสถานพยาบาล (ส.พ.16)",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 21,
                        PaymentCatalogCode = "2100700084",
                        Description = "ค่าธรรมเนียมการเปลี่ยนแปลงแก้ไขในใบอนญาตให้ดำเนินการสถานพยาบาล",
                        Amount = 100,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 22,
                        PaymentCatalogCode = "2100700083",
                        Description = "ค่าธรรมเนียมการเปลี่ยนแปลงแก้ไขในใบอนุญาตให้ประกอบกิจการสถานพยาบาล",
                        Amount = 100,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 23,
                        PaymentCatalogCode = "2100700082",
                        Description = "ค่าธรรมเนียมใบแทนใบอนุญาตให้ดำเนินการสถานพยาบาล",
                        Amount = 200,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 24,
                        PaymentCatalogCode = "2100700081",
                        Description = "ค่าธรรมเนียมใบแทนใบอนุญาตให้ประกอบกิจการสถานพยาบาล",
                        Amount = 200,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },

                    new PaymentCatalog
                    {
                        Order = 25,
                        PaymentCatalogCode = "2100700086",
                        Description = "ค่าธรรมเนียมการประกอบกิจการสถานพยาบาล ไม่เกิน 10 เตียง รายปี",
                        Amount = 500,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 26,
                        PaymentCatalogCode = "2100700087",
                        Description = "ค่าธรรมเนียมการประกอบกิจการสถานพยาบาล 10-25 เตียง รายปี",
                        Amount = 1250,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 27,
                        PaymentCatalogCode = "2100700088",
                        Description = "ค่าธรรมเนียมการประกอบกิจการสถานพยาบาล 25-50 เตียง รายปี",
                        Amount =  2500,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 28,
                        PaymentCatalogCode = "2100700089",
                        Description = "ค่าธรรมเนียมการประกอบกิจการสถานพยาบาล 50-100 เตียง รายปี",
                        Amount =  5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 29,
                        PaymentCatalogCode = "2100700090",
                        Description = "ค่าธรรมเนียมการประกอบกิจการสถานพยาบาล เกิน 100 เตียง  รายปี",
                        Amount = 5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 30,
                        PaymentCatalogCode = "2100700091",
                        Description = "ค่าธรรมเนียมการประกอบกิจการสถานพยาบาล 101 เตียง ขึ้นไป รายปี",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 31,
                        PaymentCatalogCode = "2100700085",
                        Description = "ค่าธรรมเนียมการประกอบกิจการคลีนิก รายปี",
                        Amount = 500,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 32,
                        PaymentCatalogCode = "2100700075",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ดำเนินการสถานพยาบาล ไม่เกิน 10 เตียง",
                        Amount = 500,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 33,
                        PaymentCatalogCode = "2100700076",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ดำเนินการสถานพยาบาล 10-25 เตียง",
                        Amount = 1250,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 34,
                        PaymentCatalogCode = "2100700077",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ดำเนินการสถานพยาบาล 25-50 เตียง",
                        Amount = 2500,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 35,
                        PaymentCatalogCode = "2100700078",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ดำเนินการสถานพยาบาล 50-100 เตียง",
                        Amount = 5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 36,
                        PaymentCatalogCode = "2100700079",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ดำเนินการสถานพยาบาล เกิน 100 เตียง",
                        Amount = 5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 37,
                        PaymentCatalogCode = "2100700080",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ดำเนินการสถานพยาบาล 101 เตียง ขึ้นไป",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 38,
                        PaymentCatalogCode = "2100700068",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ประกอบกิจการสถานพยาบาล ไม่เกิน 10 เตียง",
                        Amount = 2000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 39,
                        PaymentCatalogCode = "2100700069",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ประกอบกิจการสถานพยาบาล 10-25 เตียง",
                        Amount = 5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 40,
                        PaymentCatalogCode = "2100700070",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ประกอบกิจการสถานพยาบาล 25-50 เตียง",
                        Amount = 10000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 41,
                        PaymentCatalogCode = "2100700071",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ประกอบกิจการสถานพยาบาล 50-100 เตียง",
                        Amount = 20000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 42,
                        PaymentCatalogCode = "2100700072",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ประกอบกิจการสถานพยาบาล เกิน 100 เตียง",
                        Amount = 20000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 43,
                        PaymentCatalogCode = "2100700073",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ประกอบกิจการสถานพยาบาล 101 เตียง ขึ้นไป",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 44,
                        PaymentCatalogCode = "2100700074",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ดำเนินการคลินิก",
                        Amount = 250,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 45,
                        PaymentCatalogCode = "2100700067",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ประกอบกิจการคลินิก",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 46,
                        PaymentCatalogCode = "2100700106",
                        Description = "ค่าธรรมเนียมต่ออายุใบอนุญาตให้ประกอบกิจการสปา ไม่เกิน 400 ตร.ม.",
                        Amount = 6000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 47,
                        PaymentCatalogCode = "2100700115",
                        Description = "ค่าธรรมเนียมต่อายุใบอนุญาตประกอบกิจการนวดเพื่อเสริมความงาม",
                        Amount = 5000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2019-12-17","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },

                    new PaymentCatalog
                    {
                        Order = 48,
                        PaymentCatalogCode = "2100700128",
                        Description = "ค่าขึ้นทะเบียนและรับใบอนุญาตฯ สาขาการแพทย์แผนจีน",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 49,
                        PaymentCatalogCode = "2100700122",
                        Description = "ค่าขึ้นทะเบียนและรับใบอนุญาตฯ สาขากิจกรรมบำบัด",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 50,
                        PaymentCatalogCode = "2100700127",
                        Description = "ค่าขึ้นทะเบียนและรับใบอนุญาตฯสาขากายอุปกรณ์",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 51,
                        PaymentCatalogCode = "2100700123",
                        Description = "ค่าขึ้นทะเบียนและรับใบอนุญาตฯสาขาการแก้ไขความปกติของการสื่อความหมาย",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 52,
                        PaymentCatalogCode = "2100700126",
                        Description = "ค่าขึ้นทะเบียนและรับใบอนุญาตฯสาขาจิตวิทยาคลินิก",
                        Amount = 1000l,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 53,
                        PaymentCatalogCode = "2100700125",
                        Description = "ค่าขึ้นทะเบียนและรับใบอนุญาตฯสาขารังสีเทคนิค",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 54,
                        PaymentCatalogCode = "2100700124",
                        Description = "ค่าขึ้นทะเบียนและรับใบอนุญาตฯสาขาเทคโนโลยีหัวใจและทรวงอก",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 55,
                        PaymentCatalogCode = "2100700141",
                        Description = "ค่าคำร้องต่าง ๆ ผู้ประกอบโรคศิลปะ",
                        Amount = 50,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 56,
                        PaymentCatalogCode = "2100700082",
                        Description = "ค่าธรรมเนียมใบแทนใบอนุญาตให้ดำเนินการสถานพยาบาล",
                        Amount = 200,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 57,
                        PaymentCatalogCode = "2100700081",
                        Description = "ค่าธรรมเนียมใบแทนใบอนุญาตให้ประกอบกิจการสถานพยาบาล",
                        Amount = 200,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 58,
                        PaymentCatalogCode = "2100700143",
                        Description = "ค่าปรับตามมาตรา 20 พรบ.สถานพยาบาล",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 59,
                        PaymentCatalogCode = "2100700093",
                        Description = "ค่ายื่นใบคำขออนุมัติโฆษณาหรือประกาศเกี่ยวกับสถานพยาบาล",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 60,
                        PaymentCatalogCode = "2100700139",
                        Description = "ค่าใบแทนใบอนุญาต ผู้ประกอบโรคศิลปะ",
                        Amount = 200,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },
                    new PaymentCatalog
                    {
                        Order = 61,
                        PaymentCatalogCode = "2100700132",
                        Description = "ค่าสอบความรู้ผู้ขอขึ้นทะเบียนและรับใบอนุญาตฯสาขากิจกรรมบำบัด",
                        Amount = 1000,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 62,
                        PaymentCatalogCode = "2100700130",
                        Description = "ค่าหนังสือรับรองขึ้นทะเบียนเป็นผู้ประกอบโรคศิลปะ",
                        Amount = 100,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 63,
                        PaymentCatalogCode = "2100700131",
                        Description = "ค่าหนังสือรับรองอย่างอื่น ผู้ประกอบโรคศิลปะ",
                        Amount = 100,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 64,
                        PaymentCatalogCode = "2100700140",
                        Description = "ค่าแปลใบอนุญาตของผู้ประกอบโรคศิลปะเป็นภาษาต่างประเทศ",
                        Amount = 300,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 65,
                        PaymentCatalogCode = "2100700094",
                        Description = "อื่น ๆ (พ.ร.บ.สถานพยาบาล)",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },new PaymentCatalog
                    {
                        Order = 66,
                        PaymentCatalogCode = "2100700142",
                        Description = "อื่น ๆ (พรบ.การประกอบโรคศิลปะ)",
                        Amount = 0,
                        Category = "ค่าธรรมเนียม",
                        Type = "รายได้แผ่นดินทั้งจำนวน",
                        Version = 1,
                        ApproveStatus = true,
                        UsingStatus = true,
                        StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                        EndDate = null,
                        ExpiredDate = null,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now,
                        CreatedUserID = adminUser.Id,
                        UpdatedDate = DateTime.Now,
                        UpdatedUserID = adminUser.Id
                    },

                    // ยังไม่ต้องเอาเข้ารอก่อน
                    //new PaymentCatalog
                    //{
                    //    Order = 67,
                    //    PaymentCatalogCode = "2100700134",
                    //    Description = "ค่าสอบความรู้ผู้ขอขึ้นทะเบียนและรับใบอนุญาตฯ",
                    //    Amount = 1000,
                    //    Category = "ค่าธรรมเนียม",
                    //    Type = "รายได้แผ่นดินทั้งจำนวน",
                    //    Version = 1,
                    //    ApproveStatus = true,
                    //    UsingStatus = true,
                    //    StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                    //    EndDate = null,
                    //    ExpiredDate = null,
                    //    IsDeleted = false,
                    //    CreatedDate = DateTime.Now,
                    //    CreatedUserID = adminUser.Id,
                    //    UpdatedDate = DateTime.Now,
                    //    UpdatedUserID = adminUser.Id
                    //},
                    //new PaymentCatalog
                    //{
                    //    Order = 68,
                    //    PaymentCatalogCode = "2100700137",
                    //    Description = "ค่าสอบความรู้ผู้ขอขึ้นทะเบียนและรับใบอนุญาตฯ",
                    //    Amount = 1000,
                    //    Category = "ค่าธรรมเนียม",
                    //    Type = "รายได้แผ่นดินทั้งจำนวน",
                    //    Version = 1,
                    //    ApproveStatus = true,
                    //    UsingStatus = true,
                    //    StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                    //    EndDate = null,
                    //    ExpiredDate = null,
                    //    IsDeleted = false,
                    //    CreatedDate = DateTime.Now,
                    //    CreatedUserID = adminUser.Id,
                    //    UpdatedDate = DateTime.Now,
                    //    UpdatedUserID = adminUser.Id
                    //},
                    //new PaymentCatalog
                    //{
                    //    Order = 69,
                    //    PaymentCatalogCode = "2100700138",
                    //    Description = "ค่าสอบความรู้ผู้ขอขึ้นทะเบียนและรับใบอนุญาตฯ",
                    //    Amount = 1000,
                    //    Category = "ค่าธรรมเนียม",
                    //    Type = "รายได้แผ่นดินทั้งจำนวน",
                    //    Version = 1,
                    //    ApproveStatus = true,
                    //    UsingStatus = true,
                    //    StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                    //    EndDate = null,
                    //    ExpiredDate = null,
                    //    IsDeleted = false,
                    //    CreatedDate = DateTime.Now,
                    //    CreatedUserID = adminUser.Id,
                    //    UpdatedDate = DateTime.Now,
                    //    UpdatedUserID = adminUser.Id
                    //},
                    //new PaymentCatalog
                    //{
                    //    Order = 70,
                    //    PaymentCatalogCode = "2100700135",
                    //    Description = "ค่าสอบความรู้ผู้ขอขึ้นทะเบียนและรับใบอนุญาตฯ",
                    //    Amount = 1000,
                    //    Category = "ค่าธรรมเนียม",
                    //    Type = "รายได้แผ่นดินทั้งจำนวน",
                    //    Version = 1,
                    //    ApproveStatus = true,
                    //    UsingStatus = true,
                    //    StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                    //    EndDate = null,
                    //    ExpiredDate = null,
                    //    IsDeleted = false,
                    //    CreatedDate = DateTime.Now,
                    //    CreatedUserID = adminUser.Id,
                    //    UpdatedDate = DateTime.Now,
                    //    UpdatedUserID = adminUser.Id
                    //},
                    //new PaymentCatalog
                    //{
                    //    Order = 71,
                    //    PaymentCatalogCode = "2100700136",
                    //    Description = "ค่าสอบความรู้ผู้ขอขึ้นทะเบียนและรับใบอนุญาตฯ",
                    //    Amount = 1000,
                    //    Category = "ค่าธรรมเนียม",
                    //    Type = "รายได้แผ่นดินทั้งจำนวน",
                    //    Version = 1,
                    //    ApproveStatus = true,
                    //    UsingStatus = true,
                    //    StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                    //    EndDate = null,
                    //    ExpiredDate = null,
                    //    IsDeleted = false,
                    //    CreatedDate = DateTime.Now,
                    //    CreatedUserID = adminUser.Id,
                    //    UpdatedDate = DateTime.Now,
                    //    UpdatedUserID = adminUser.Id
                    //},
                    //new PaymentCatalog
                    //{
                    //    Order = 72,
                    //    PaymentCatalogCode = "2100700133",
                    //    Description = "ค่าสอบความรู้ผู้ขอขึ้นทะเบียนและรับใบอนุญาตฯ",
                    //    Amount = 1000,
                    //    Category = "ค่าธรรมเนียม",
                    //    Type = "รายได้แผ่นดินทั้งจำนวน",
                    //    Version = 1,
                    //    ApproveStatus = true,
                    //    UsingStatus = true,
                    //    StartDate = DateTime.ParseExact("2020-12-19","yyyy-MM-dd", CultureInfo.InvariantCulture),
                    //    EndDate = null,
                    //    ExpiredDate = null,
                    //    IsDeleted = false,
                    //    CreatedDate = DateTime.Now,
                    //    CreatedUserID = adminUser.Id,
                    //    UpdatedDate = DateTime.Now,
                    //    UpdatedUserID = adminUser.Id
                    //}
                };

                context.PaymentCatalogs.AddOrUpdate(o => o.PaymentCatalogCode, paymentCatalogs.ToArray());
                context.SaveChanges(false);
            }
        }
    }
}
