//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BizPortal.th.go.moph.fda.privus {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_AUTHEN_BYPASSSoap", Namespace="http://tempuri.org/")]
    public partial class WS_AUTHEN_BYPASS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BIZPORTAL_URLOperationCompleted;
        
        private System.Threading.SendOrPostCallback BIZPORTAL_URL_TESTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_AUTHEN_BYPASS() {
            this.Url = global::BizPortal.Properties.Settings.Default.BizPortal_th_go_moph_fda_privus_WS_AUTHEN_BYPASS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BIZPORTAL_URLCompletedEventHandler BIZPORTAL_URLCompleted;
        
        /// <remarks/>
        public event BIZPORTAL_URL_TESTCompletedEventHandler BIZPORTAL_URL_TESTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BIZPORTAL_URL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BIZPORTAL_URL(FIELDS_AUTHEN_BYPASS FIELDS) {
            object[] results = this.Invoke("BIZPORTAL_URL", new object[] {
                        FIELDS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BIZPORTAL_URLAsync(FIELDS_AUTHEN_BYPASS FIELDS) {
            this.BIZPORTAL_URLAsync(FIELDS, null);
        }
        
        /// <remarks/>
        public void BIZPORTAL_URLAsync(FIELDS_AUTHEN_BYPASS FIELDS, object userState) {
            if ((this.BIZPORTAL_URLOperationCompleted == null)) {
                this.BIZPORTAL_URLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBIZPORTAL_URLOperationCompleted);
            }
            this.InvokeAsync("BIZPORTAL_URL", new object[] {
                        FIELDS}, this.BIZPORTAL_URLOperationCompleted, userState);
        }
        
        private void OnBIZPORTAL_URLOperationCompleted(object arg) {
            if ((this.BIZPORTAL_URLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BIZPORTAL_URLCompleted(this, new BIZPORTAL_URLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BIZPORTAL_URL_TEST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BIZPORTAL_URL_TEST() {
            object[] results = this.Invoke("BIZPORTAL_URL_TEST", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BIZPORTAL_URL_TESTAsync() {
            this.BIZPORTAL_URL_TESTAsync(null);
        }
        
        /// <remarks/>
        public void BIZPORTAL_URL_TESTAsync(object userState) {
            if ((this.BIZPORTAL_URL_TESTOperationCompleted == null)) {
                this.BIZPORTAL_URL_TESTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBIZPORTAL_URL_TESTOperationCompleted);
            }
            this.InvokeAsync("BIZPORTAL_URL_TEST", new object[0], this.BIZPORTAL_URL_TESTOperationCompleted, userState);
        }
        
        private void OnBIZPORTAL_URL_TESTOperationCompleted(object arg) {
            if ((this.BIZPORTAL_URL_TESTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BIZPORTAL_URL_TESTCompleted(this, new BIZPORTAL_URL_TESTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIELDS_AUTHEN_BYPASS {
        
        private string tOKEN_KEYField;
        
        private System.DateTime cRATE_DATEField;
        
        private string cTZNOField;
        
        private string cTZNO_NAMEField;
        
        private string eMAILField;
        
        private string mOBILEField;
        
        private string tRADER_NOField;
        
        private string sYSTEM_IDField;
        
        private string gROUP_IDField;
        
        private string uRL_APPField;
        
        /// <remarks/>
        public string TOKEN_KEY {
            get {
                return this.tOKEN_KEYField;
            }
            set {
                this.tOKEN_KEYField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CRATE_DATE {
            get {
                return this.cRATE_DATEField;
            }
            set {
                this.cRATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string CTZNO {
            get {
                return this.cTZNOField;
            }
            set {
                this.cTZNOField = value;
            }
        }
        
        /// <remarks/>
        public string CTZNO_NAME {
            get {
                return this.cTZNO_NAMEField;
            }
            set {
                this.cTZNO_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        public string MOBILE {
            get {
                return this.mOBILEField;
            }
            set {
                this.mOBILEField = value;
            }
        }
        
        /// <remarks/>
        public string TRADER_NO {
            get {
                return this.tRADER_NOField;
            }
            set {
                this.tRADER_NOField = value;
            }
        }
        
        /// <remarks/>
        public string SYSTEM_ID {
            get {
                return this.sYSTEM_IDField;
            }
            set {
                this.sYSTEM_IDField = value;
            }
        }
        
        /// <remarks/>
        public string GROUP_ID {
            get {
                return this.gROUP_IDField;
            }
            set {
                this.gROUP_IDField = value;
            }
        }
        
        /// <remarks/>
        public string URL_APP {
            get {
                return this.uRL_APPField;
            }
            set {
                this.uRL_APPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BIZPORTAL_URLCompletedEventHandler(object sender, BIZPORTAL_URLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BIZPORTAL_URLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BIZPORTAL_URLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BIZPORTAL_URL_TESTCompletedEventHandler(object sender, BIZPORTAL_URL_TESTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BIZPORTAL_URL_TESTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BIZPORTAL_URL_TESTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591