// <auto-generated />
namespace BizPortal.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterCategoryView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterCategoryView));
        
        string IMigrationMetadata.Id
        {
            get { return "201603310855213_AlterCategoryView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
