// <auto-generated />
namespace BizPortal.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class memberManageService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(memberManageService));
        
        string IMigrationMetadata.Id
        {
            get { return "201811251909282_memberManageService"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
